### ISSUE TITLE
enhance documentation of fishbase table / columns

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#10]
@agruss2 suggested to enhance the documentation of tables and columns related to https://github.com/ropensci/fishbaseapi/ documentation . He needs this to complete the fishbase-osmose mapping that is defined here: https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv . Skit and Deng are working on providing this.

**Comment by agruss2** [comment]
Deng & Skit - Could you please provide this to us? Also, could you please provide your GitHub usernames? This way I could make use of @mentions when I writte down or comment on issues. Thanks.

**Comment by agruss2** [comment]
@jhpoelen 
I still have not received anything from Deng and Skit; I am stuck because of this. I am going to send another email to the group to request a "dictionnary" of FishBase tables and columns. Fingers crossed that we will get something soon :smiley:

**Comment by jhpoelen** [comment]
related to #27 . Please let me know how I can help with this.

**Comment by jhpoelen** [comment]
I created a wiki page https://github.com/jhpoelen/fb-osmose-bridge/wiki/Fishbase-Schema-Documentation that described our current strategy for documenting database tables. The fishbaseapi team maintains the documentation https://github.com/ropensci/fishbaseapi/tree/master/docs/docs-sources and I suggest we continue to work with them to fill in missing documentation using the familiar github mechanisms such as pull requests and issues.
