### ISSUE TITLE
Provide the lists of species in the README file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#100]
@jhpoelen Please have a look at the README file provided in Issue #99 
I would like the first tab of the README file to provide the list of species making up each of the focal functional groups represented in the OSMOSE model. 
I would like the second tab of the README file to provide the list of species making up each of the background functional groups represented in the OSMOSE model.

**Comment by jhpoelen** [comment]
I can see how a README file can be useful, I would, however, suggest to use an open format like txt, csv or json to capture this information. Xlsx files are messy generate, transform and export. 

How about one additional csv file (e.g. ```functional_groups.csv```) that list all species and their associated groups.

Something like:

 group name | group type | species name | species fishbase url 
 --- | --- | --- | ---
 my first | focal | Donaldo duckens | http://fishbase.org/summary/123
 my last | background | Minio mousus | http://fishbase.org/summary/456

**Comment by agruss2** [comment]
@jhpoelen Regarding the README file itself, the reason why I am using a .xlsx format is that .txt or .csv files do not allow one to define several tabs. For the sake of readability, the README file needs to have several tabs. 
Now, I agree with you that the list of functional groups should not be provided in the README file, but in a separate .csv file. 
Therefore, I removed the first two tabs of the README file, whose latest version is attached here: 
[README.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/824873/README.xlsx)

Regarding the additional csv file ("Functional_groups.csv") that list all species and their associated groups? indeed the following format would be excellent:
Functional group name 	Functional group type 	Species name 	Species FishBase/SeaLifeBase URL
Myfirst 	Focal 	Donaldo duckens 	http://fishbase.org/summary/123
Mylast 	Background 	Minio mousus 	http://fishbase.org/summary/456

**Comment by jhpoelen** [comment]
file ```functional_groups.csv``` is now generated with discussed content. 

Please verify.

**Comment by agruss2** [comment]
@jhpoelen Perfect, many thanks! I can close this issue now.
