### ISSUE TITLE
Default value of the plankton.accessibility2fish.plk* parameters

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#101]
@jhpoelen The plankton.accessibility2fish.plk* parameters are parameters estimated during the calibration process of the OSMOSE model. The value that the bridge should define for these parameters is: 0.

**Comment by jhpoelen** [comment]
Implemented as suggested. Please verify.

**Comment by agruss2** [comment]
The present issue has been resolved. Therefore, I am closing it today.
