### ISSUE TITLE
show error message in UI when osmose_config.zip fails to generate

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#102]
expected: Whenever a call to the configuration api returns an error (non-200 ok), the user should be notified.

observated: when a call to configuration timed-out and created a 503, the user was not notified. 

see #66 .

**Comment by jhpoelen** [comment]
@FIN-casey @FIN-JBarile  this is a UI issue - which label do we use for that?

**Comment by FIN-casey** [comment]
@jhpoelen @agruss2 , I implemented the display of error message when the osmose config fails to generate. The displayed message is "Generating configuration is not successful." in red font.

Please check so we can close this issue.

**Comment by agruss2** [comment]
@jhpoelen I have made several tests with the UI, which have all succeeded; therefore, I am not able to check what Casey recently implemented. Please check, and close this issue if this is relevant.

**Comment by jhpoelen** [comment]
Here's what I did to confirm the behavior:

1. select "gulf of mexico"
2. proceed to submit page
3. turn off network on my machine
4. click "submit"

Expected json configuration is now available for download.

I am sure there's many ways to make the UI a little more intuitive, and I am sure we'll come up with some ways as we expand the user audience.
