### ISSUE TITLE
provide download link for configuration.json in final configuration generation step

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#104]
Currently, the wizard created a configuration json file and sends it to the configuration api to generate the osmose_config.zip . If something goes wrong in the osmose_config.zip, it takes some technical skills to retrieve the provided configuration json.

Suggest to provide a download link for the generated configuration json that is used to send to the configuration api. This way, Arnaud, or any other user, can easily check what the wizard generated for the configuration api to consume.

**Comment by jhpoelen** [comment]
@FIN-casey @FIN-JBarile this is a suggestion for a UI features that would help debugging easier. Which label would you like to use for this?

**Comment by FIN-casey** [comment]
@jhpoelen @agruss2 , I implemented the addition of download link for the generated configuration JSON, when the call doesn't return the osmose_config.zip.

The text for the download link is "Click here to download the configuration JSON".

Please check so that we can close the issue.

**Comment by agruss2** [comment]
@jhpoelen I think that this issue can now be closed; please close it if you feel the same. Otherwise, please let Casey know if something else should be done here. Thanks a lot.
