### ISSUE TITLE
Need to implement the extraction of default functional groups when the user selected the Country/FAO combination 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#105]
The extraction of default functional groups when the user selected the Country/FAO combination needs to be implemented.

**Comment by FIN-casey** [comment]
Hi @agruss @FIN-JBarile 
I implemented this in the UI. Currently, the subcountry is not yet included in the filtering of data. Please check so we can close the issue. Thanks

**Comment by agruss2** [comment]
@FIN-casey @FIN-JBarile Many thanks. I just checked this and it is working; please feel free to close the present issue when you think it is relevant.

**Comment by agruss2** [comment]
@FIN-casey Since the subcountry is not included in the filtering of data yet, should we close this issue or not? Thanks

**Comment by FIN-casey** [comment]
@agruss2 @FIN-JBarile I am done implementing the extraction of subcountry in Step 1. Please verify so we can close this issue. Thanks

**Comment by agruss2** [comment]
@FIN-casey @FIN-JBarile Perfect, I just checked and everything is working as intended. Therefore, let's close the present issue. Many thanks Casey !
