### ISSUE TITLE
UI Final Step

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#107]
@FIN-casey 
Currently, the main text in UI Final Step is as follows:

We now have all the necessary information to generate configuration files for your OSMOSE model.
When you are ready, press "Download configuration files". You will then get a zip file containing (1) all the OSMOSE configuration files; and (2) a README file listing the species making up each of the functional groups of your OSMOSE model, and detailing which parameter estimates were obtained through FishBase/SeaLifeBase and which parameter estimates remain to be entered by you.
*For technical assistance on OSMOSE, please contact Philippe Verley (philippe.Verley@ird.fr) or post a question on: http://www.osmose-model.org/forum.

--> Please replace the text above by the following one: 

We now have all the necessary information to generate configuration files for your OSMOSE model. These configuration files are compatible with OSMOSE 3 Update 2, which is available for download here: http://www.osmose-model.org/downloads 
When you are ready, press "Download configuration files". You will then get a zip file containing (1) all the OSMOSE configuration files; (2) a file called “functional_groups.csv”, which lists the species making up each of the functional groups of your OSMOSE model; and (3) a README file detailing which parameter estimates were obtained through FishBase/SeaLifeBase and which parameter estimates remain to be entered by you.
*For technical assistance on OSMOSE, please contact Philippe Verley (philippe.Verley@ird.fr) or post a question on: http://www.osmose-model.org/forum

**Comment by FIN-casey** [comment]
Hi @agruss2 
I implemented the changes in the Final Step in the UI. Please verify.

**Comment by agruss2** [comment]
@FIN-casey Perfectn many thanks! I can now close the present issue.
