### ISSUE TITLE
regarding definition of female:male sex ratio in OSMOSE is a quantity lower than 1

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#108]
@agruss2 in fishbase-mapping.csv, you mentioned that "female:male sex ratio in OSMOSE is a quantity lower than 1". Right now the female:male sex ratio is calculated by taking fishbase sexratio:

(spawning.SexRatiomid) / 100

This produces sexratio values between 0 and 1. 

However, a true female:male sex ratio would be calculated as:

female / male = (spawning,SexRatiomid) / (100 - spawning,SexRatiomid)

However, this ratio is not constrained to the range between 0 and 1. For example, consider a value spawning.SexRatiomid of 75, and a ratio would be 75 / (100 - 75) = 75 / 25 = 3 . Also, this ratio would not be defined is only females are spawned (e.g 100 / 0).

Please clarify the female:male ratio.

**Comment by agruss2** [comment]
@jhpoelen My definition of "sex ratio" in OSMOSE was inaccurate; sorry about that!
Sex ratio in OSMOSE is not "female:male sex ratio", but rather the "percentage of spawning females in the spawning stock". 
This means that, if the female male sex ratio is 4:1 (i.e., 4 females for 1 male), then the "sex ratio in OSMOSE", i.e., the "percentage of spawning females in the spawning stock", is given by:
(4)/(4+1) = 0.8

Could you please update the API accordingly? Once this is done, please let me know, and I will update "fsihbase-mapping.csv" and README files and will close the present issue if appropriate.

**Comment by jhpoelen** [comment]
@agruss2 thanks for the update. This definition is in line with the method already implemented. Please verify that the osmose sexratio is calculated as expected.

**Comment by agruss2** [comment]
@jhpoelen I just checked and OSMOSE sex ratio is being estimated as expected; many thanks! Therefore, I am closing the present issue today.
