### ISSUE TITLE
fishbase eggs table is missing: species.egg.size.sp, species.egg.weight.sp cannot be calculated: 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#109]
as discussed in https://github.com/jhpoelen/fb-osmose-bridge/issues/97#issuecomment-284465610 .

Without the ```eggs``` table, estimates for the following parameters of the "osm_param-species.csv" config file cannot be determined:
(1) species.egg.size.sp*
(2) species.egg.weight.sp*

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo Please help Jorrit here; many thanks!

**Comment by FIN-JBarile** [comment]
@jhpoelen @agruss2   I have requested Scott (rOpenSci) to publish the eggs table in the FishBase API and got a positive reply. Shall await implementation as they are going to put up the latest version of the database soon as well.

**Comment by agruss2** [comment]
@FIN-JBarile Sounds good, thanks.

**Comment by jhpoelen** [comment]
Glad to hear that the eggs table will be added soon. Once the table is available, I'll prepare a new release of the fishbase cache (see https://github.com/jhpoelen/fishbase_archiver/releases ) and update the bridge to point to the latest release.

**Comment by FIN-JBarile** [comment]
@jhpoelen @agruss2 Scott has added the EGGS table in the [API](https://fishbase.ropensci.org/heartbeat/). Note though that this is still based on the last version of the database. They are still working on the update.

**Comment by jhpoelen** [comment]
@FIN-JBarile @Dengaloo thanks for working with @sckott to add the eggs table. I was able to access the table using the ropensci's fishbase api and created archives for it using https://github.com/jhpoelen/fishbase_archiver .

@agruss2 please confirm that the egg weights are now being populated as expected.

**Comment by sckott** [comment]
FYI, will be rolling out versioned access soon - versioned that is with respect to database version, there's 2015, 2016, and 2017 versions

**Comment by agruss2** [comment]
@jhpoelen 
I just used the current version of the bridge to request parameters for the Gulf of Mexico. 
All the egg sizes (i.e., egg diameters) provided by the bridge are at their default values, i.e., 0.1 cm. 
If an egg has a diameter D of 0.1 cm, then its radius is equal to: r = D/2 = 0.05 cm. Then, its weight should be equal to: (1.025).(4/3).pi.r3 = (1.025).(4/3).pi.(0.000125) = 0.00053669 g
However, the value provided by the bridge is: 0.0005386 g
Could you please fix this issue?

**Comment by jhpoelen** [comment]
@agruss2 nice catch. Reproduced and fixed the issue. The root cause was a typo in the egg density estimate (0.0254 --> 0.025). Please confirm.

**Comment by agruss2** [comment]
@jhpoelen I just made a new test, but the value provided by the bridge is still 0.0005386 g.

**Comment by jhpoelen** [comment]
@agruss2 thanks for being patient. It turned out that the calculated egg estimate was using an incorrect parameter as input: this caused the unit tests to pass, but prevented correct calculated of the egg weight. I've fixed the issue and double checked the outcome using the configuration wizard. Please confirm that outcome is now as expected.

**Comment by agruss2** [comment]
@jhpoelen I just checked and outcome is now as expected; many thanks!

**Comment by agruss2** [comment]
@jhpoelen It seems that this issue has been addressed; therefore, I am deciding to close it now.
