### ISSUE TITLE
Plankton species included in SeaLifeBase

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#116]
@Dengaloo @FIN-JBarile 
Today, I ran a test with the bridge between FishBase/SeaLifeBase and OSMOSE, where I requested parameter estimates for an OSMOSE model of the Iceland Shelf/Sea. 
I noticed that one species in the list of species is a copepod species (zooplankton): _Calanus finmarchicus_. 

--> Questions: 
(1) Are all types of zooplanton species included in SeaLifeBase? Or are only a few zooplankton species (for example, only copepod species) included in SeaLifeBase? 
(2) Does SeaLifeBase includes information for phytoplankton species? 

Your answers will be important to inform the user about what the bridge between FishBase/SeaLifeBase and OSMOSE will provide to them, and what they will need to find elsewhere.

**Comment by FIN-JBarile** [comment]
@agruss2 Just quick answers for now. 
(1) All zooplanktons should be covered by SeaLifeBase. I can give data richness (as you have defined) profile for this group in more detail once I consult with SeaLifeBase staff.
(2) There are phytoplanktons in SeaLifeBase as well (approx 1200 species). However, only 80 species are categorized into the functional groups and all have data richness value =1.

@Dengaloo

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo This is very useful information, many thanks!
I'll soon create a new GitHub issue to explain how I think we should deal with phytoplankton and zooplankton. 
I think that it is not reasonable to define functional groups for the user without having at least one phytoplankton group and one zooplankton group. 
I am going to close the present issue now, But please be on the lookout for a new GitHub issue on the topic of phytoplankton and zooplankton.
