### ISSUE TITLE
Parameter values for the zooplankton group

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#121]
I just ran a test where I queried parameters for an OSMOSE model for the Iceland Shelf/Sea ecosystem.
I did not touch anything in Step 2 and downloaded the config zip file.
However, when I looked at the "osm_param-ltl.csv" file (provided here in the .xlsx format: 
[osm_param-ltl.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/1118057/osm_param-ltl.xlsx)), the parameter values for the zooplankton group were all "NA", while they should be as follows:
(i) Minimum size: 0.002 cm (OSMOSE parameter: “plankton.size.min.plkX”);
(ii) Maximum size: 0.3 cm (OSMOSE parameter: “plankton.size.max.plkX”);
(iii) Trophic level: 2 (OSMOSE parameter: "plankton.TL.plkX").

Could you please correct for this?

**Comment by FIN-casey** [comment]
The generation of osm_param-ltl.csv file is done by the API, but will the parameters be  populated once the zooplanktons group is identified? Please verify, @jhpoelen.

**Comment by agruss2** [comment]
@FIN-casey @jhpoelen I just ran a test and we are still having the same issue. 
@FIN-casey Jorrit is currently on vacation and will be able to address the present GitHub issue only when he is back to work, which will be August, 10th or after.

**Comment by FIN-casey** [comment]
@agruss2 I believe this is an issue for the API.

**Comment by agruss2** [comment]
@FIN-casey I agree that this is an API issue that @jhpoelen will solve after August, 10th.

**Comment by jhpoelen** [comment]
As also observed in https://github.com/jhpoelen/fb-osmose-bridge/issues/115#issuecomment-322600357, the lists of taxa associated with zooplankton and phytoplankton are empty. 

@FIN-casey is there anything that needs to happen to populate the zooplankton taxon list?

Snippet of functional groups sent from UI to API for default Iceland Shelf/Sea -

```
...
{
      "name": "zooplankton",
      "type": "background",
      "taxa": []
    },
    {
      "name": "phytoplankton",
      "type": "background",
      "taxa": []
    }
...
```

**Comment by FIN-casey** [comment]
@jhpoelen As there are no species included in zooplankton and phytoplankton in previous steps, the generated JSON won't have any species as expected. 

Do you mean to populate the taxon list with all the species included in the zooplankton group without filter on data richness on the generated JSON only?

**Comment by jhpoelen** [comment]
@FIN-casey thanks for being patient. It turned out that I didn't re-read the issue properly.

@agruss2 I've added default values for zooplankton in addition to pre-existing phytoplankton mappings. Also, I've re-created the default Iceland Shelf/Sea to check that zooplankton default are now populated as expected. See [osmose_config (7).zip](https://github.com/jhpoelen/fb-osmose-bridge/files/1229127/osmose_config.7.zip) generated 16 Aug 2017. 

Note that you can change the defaults for zoo/phytoplankton groups independently using fishbase-mapping-zooplankton.csv fishbase-mapping-phytoplankton.csv resp. in https://github.com/jhpoelen/fb-osmose-bridge/tree/master/src/main/resources/com/github/jhpoelen/fbob .

Please confirm by closing this issue.

**Comment by agruss2** [comment]
@jhpoelen I just ran a test where I queried parameters for an OSMOSE model for the Iceland Shelf/Sea ecosystem.
When I looked at the "osm_param-ltl.csv" file, the parameter values for the zooplankton group were the same as those for the phytoplankton group, while they should be as follows:
(i) Minimum size: 0.002 cm (OSMOSE parameter: “plankton.size.min.plkX”);
(ii) Maximum size: 0.3 cm (OSMOSE parameter: “plankton.size.max.plkX”);
(iii) Trophic level: 2 (OSMOSE parameter: "plankton.TL.plkX").

Could you please correct for this?
Many thanks!

**Comment by jhpoelen** [comment]
You should be able to edit https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping-zooplankton.csv and apply the changes yourself. Happy to do for you if you don't feel comfortable making the change yourself.

Ideally, you should not need folks like me to tweak this kind of biologically relevant configuration to avoid unnecessary delay and frustration.
