### ISSUE TITLE
Avoiding redundancies as regards plankton groups

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#122]
@FIN-casey @FIN-JBarile @Dengaloo
I ran another test with the bridge between FishBase/SeaLifeBase and OSMOSE, where I queried parameters for an OSMOSE model for the Iceland Shelf/Sea ecosystem. I did not touch anything in Step 2, except that I defined the "invertpelagicsm" functional group as a "background" functional group. The "invertpelagicsm" functional group includes only one species: _Calanus finmarchicus_ (Maxillopoda); see:
functional_groups.xlsx
However, as you know, _Calanus finmarchicus_ belongs to the zooplankton. Like pretty much all the zooplankton species included in SeaLifeBase, _Calanus finmarchicus_ is a data-poor species and, therefore, the bridge between FishBase/SeaLifeBase and OSMOSE provides only NA's for this species.
Therefore, I think that we should find a way to: (1) make the bridge between FishBase/SeaLifeBase and OSMOSE define only general "phytoplankton" and "zooplankton" background functional groups, as is presently the case; and (2) prevent the bridge from defining other phytoplankton and zooplankton groups/species in the table provided in Step 2.

This may be a little bit technical to implement.

Is there a way to identify which of the numerous species included in SeaLifeBase belong to the phytoplankton or zooplankton?
Or are we only able to determine the class, phylum, order, etc. to which the species that are included in SeaLifeBase belong?

In any case, it would be good to implement what I described above, so as to avoid defining redundant plankton groups for which the bridge between FishBase/SeaLifeBase and OSMOSE will only provide NA's.

**Comment by FIN-JBarile** [comment]
@agruss2 with help from Jenks of the SeaLifeBase team, phytoplankton and zooplanton species are now filtered out of the dataset for non-fish. @FIN-casey will incorporate that in the interface.

**Comment by agruss2** [comment]
@FIN-JBarile Thanks a lot to you, Jenks and the SeaLifeBase team for this, this is really great!
@FIN-casey Please let me know when changes have been completed; I will then run a new test with the bridge between FishBase/SeaLifeBase and OSMOSE. Many thanks.

**Comment by FIN-JBarile** [comment]
@agruss2 Here's the data profile for the additional functional groups: phytoplankton and zooplankton - 
[Planktons_DataProfile.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/1200249/Planktons_DataProfile.zip). Phytoplanktons have datarichness=1 for all records. Our filter is datarichnes >= 2. Thus, no list of species may be given in Step 2 for Phytoplanktons. Is it ok to just include all phytoplanktons anyhow?

@FIN-casey please monitor Arnaud's reply to this comment in order for you to proceed accordingly. Thanks.

**Comment by agruss2** [comment]
@FIN-JBarile @FIN-casey Thanks a lot for spreadsheet. 

Regarding phytoplankton species - There is nothing to do here, since all have datarichness = 1 and, therefore, individual phytoplankton species will never appear in the Table provided in Step 2. 

Regarding zooplankton species - Some have datarichness between 2 and 13, which means that there is a risk that they may appear in the Table provided in Step 2 in addition to the mandatory "zooplankton" background functional group. 
To keep things simple, I recommend that we do not allow any zooplankton species to appear in Table 2 and define only one single generic "zooplankton" background functional group, as is presently the case. 
What this means is that the bridge between FishBase/SeaLifeBase should consider the information provided in the "Planktons_DataProfile" spreadsheet and make sure that none of the species listed in the "Planktons_DataProfile" spreadsheet appears in the Table provided in Step 2. This means, for example, that _Calanus finmarchicus_ (Maxillopoda) should not appear in Table 2 if the user requests parameter estimates for the Iceland Shelf/Sea ecosystem. 

@FIN-casey  Please let me know if you can implement this on your own. Or if changes are also needed in the API; in this latter case, I will define the present issue as both a UI and an API issue and will request Jorrit's help. 

Many thanks!

**Comment by FIN-casey** [comment]
@agruss2 @FIN-JBarile The datasets are now updated based on the datasets sent by @FIN-JBarile, wherein the zooplankton and phytoplankton species are not included. Those species should now not be shown in the other functional group, either by default populating of the table or by adding specific species or by adding class.

To test this changes, make sure to clear your browser cache.

**Comment by agruss2** [comment]
@FIN-casey @FIN-JBarile 
I just ran a test where I queries parameter estimates for an OSMOSE model of the Iceland Shelf/Sea. I examined results, and I can confirm that the present issue has been fully solved and can now be closed. 
Many thanks for everything.
