### ISSUE TITLE
Remove the message "Please select at least one background functional group."

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#127]
@FIN-casey 
Since the "phytoplankton" and "zooplankton" groups are now defined as background functional groups for any OSMOSE model, the following message should not appear anymore when the user moves to Step 3: 
"Please select at least one background functional group."
Could you please make sure that this message does not appear anymore? 
Many thanks.

**Comment by FIN-casey** [comment]
@agruss2 This is now implemented in the wizard. Please verify.
Thanks.

**Comment by agruss2** [comment]
@FIN-casey Many thanks; the present issue has been solved and can now be closed.
