### ISSUE TITLE
Modifying some text on the UI final page

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#128]
Regarding the UI final step ("Download configuration files for your OSMOSE model") -
Could you please replace the following text:

> When you are ready, press "Download configuration files". 

with that one:

> When you are ready, press "Submit". 

?
Many thanks.

**Comment by FIN-casey** [comment]
@agruss2 The change is now implemented in the UI final step.
Please verify.

**Comment by agruss2** [comment]
The present issue has been solved; I am therefore going to close it. Many thanks.
