### ISSUE TITLE
Inserting some text on the UI final page

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#129]
Regarding the UI final step ("Download configuration files for your OSMOSE model") -
After:

> *For technical assistance on OSMOSE, please contact Philippe Verley (philippe.Verley@ird.fr) or post a question on: http://www.osmose-model.org/forum.

Could you please insert the following text **in red** 

> Please be patient. The generation of your zip file may take a while. 

Many thanks.

**Comment by FIN-casey** [comment]
@agruss2 The change is now implemented.
Please verify.

**Comment by agruss2** [comment]
The present issue has been solved; I am therefore going to close it. Many thanks.
