### ISSUE TITLE
add osmose configuration properties to mapping table

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#13]
as discussed in meeting Feb 22, 2015 with Deng, Skit, Jim, Jorrit and Arnaud: add osmose properties that need mapping in the middle columns of https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv so that we can see which properties still need a fishbase table/column to be coupled to.

**Comment by agruss2** [comment]
@jhpoelen This is done. We now need to hear from Skit and Deng about the exact meaning of the different FishBase parameters.

**Comment by jhpoelen** [comment]
@agruss2 thanks! closing issue.
