### ISSUE TITLE
Providing only species making up the functional groups in the "functional_groups.csv" file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#130]
Only the species making up the functional groups of the OSMOSE model should be provided in the "functional_groups.csv" file. 
In other words, the "functional_groups.csv" file should not include all the extra species that were considered by the bridge between FishBase/SeaLifeBase and OSMOSE for trying to obtain parameter values for the functional groups. 
Many thanks.

**Comment by jhpoelen** [comment]
@agruss2 please verify expected behavior is now present by closing this issue.

**Comment by agruss2** [comment]
@jhpoelen I just checked and I can confirm that this issue has been solved; many thanks.
