### ISSUE TITLE
Providing estimates for the predator/prey size ratios

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#131]
I just updated the "fishbase-mapping.csv" file to explain where to look for estimates for the minimum and maximum predator/prey size ratios. 
I also updated the default values of the size ratios in the "fishbase-mapping.csv" file. 

Please note that the "predation.predPrey.sizeRatio.max.spX" parameter in OSMOSE is the minimum predator/prey size ratio of functional group X, while the "predation.predPrey.sizeRatio.min.spX" parameter in OSMOSE is the maximum predator/prey size ratio of functional group X. This is because the OSMOSE modeling platform inverts the size ratios before using them in simulations. 

Please also note that the estimates of minimum and maximum predator/prey size ratios that were integrated in FishBase/SeaLifeBase are tentative, and will be soon updated once #32 has been solved. 

Many thanks.

**Comment by jhpoelen** [comment]
I've incorporated the preliminary estimate tables for fishbase and sealifebase as provided in #32 . This should activate the mapping you defined in ```fishbase_mapping.csv```. Please confirm.

**Comment by agruss2** [comment]
@jhpoelen I just ran a test for the Iceland Shelf/Sea ecosystem, and noticed the presence of 0.0's for the "predation.predPrey.sizeRatio.max.sp*" parameters and of NA's for the "predation.predPrey.sizeRatio.min.sp*" parameters; see 
[osm_param-predation.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/1294771/osm_param-predation.xlsx)
However, as per the "fishbase-mapping.csv" file, the default value of the "predation.predPrey.sizeRatio.max.sp*" parameters should be 3.5, and the default value of the "predation.predPrey.sizeRatio.min.sp*" parameters should be 30.0. 
Could you please correct for this, and then let me know when it is done so that I can run a new test? 
Thanks a lot!

**Comment by jhpoelen** [comment]
Thanks for sharing your detailed example.

A quick glance at the file shared in #32 by @FIN-JBarile and @Dengaloo seems to suggest that zeros exist in PredPreyRatioMin as well as NAs in both PredPreyRatioMin and PredPreyRatioMax.

Would you expect these values in the ```estimate``` table in fishbase/sealifebase?

```R
> est <- read.csv('estimate_fishbase.tsv', sep='\t')
> summary(est$PredPreyRatioMin)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.080   0.190   0.472   0.460  27.730   29990 
> summary(est$PredPreyRatioMin)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.080   0.190   0.472   0.460  27.730   29990 
> summary(est$PredPreyRatioMax)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.090   1.950   4.475   9.583  10.090 419.700   29990  
```

**Comment by jhpoelen** [comment]
Correction - please note that the NAs were introduced by the conversion from csv to tsv using R. I've corrected the issue and updated the patch release at https://github.com/jhpoelen/fishbase_archiver/releases/tag/v0.2.1-patch accordingly. 

Note that this still leaves the observed zeros for the PredPreyRatioMin . Perhaps a rounding error?

**Comment by agruss2** [comment]
@jhpoelen Many thanks for your hard work on this. 
The problem with NA's that I mentioned ealier has been solved. 
A lot of values do not make sense, but this is because the estimates provided in the FishBase table need to be updated after we have fitted more appropriate statistical models to the data (see #32). 
Thus, the present issue can be closed.
