### ISSUE TITLE
Modifying some text on the UI final page (2)

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#135]
Regarding the UI final step ("Download configuration files for your OSMOSE model") -
Could you please replace the following text:

> (philippe.Verley@ird.fr)

with that one (i.e., verley with a lower case v instead of a upper case):

> (philippe.verley@ird.fr)

?
Many thanks.

**Comment by FIN-casey** [comment]
@agruss2 The change is now implemented. 
Please verify.

**Comment by agruss2** [comment]
The present issue has been solved; I am therefore going to close it. Many thanks.
