### ISSUE TITLE
Modifying some text on the UI final page

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#137]
Regarding the UI final step ("Download configuration files for your OSMOSE model") -
Could you please replace the following text:

> please contact Philippe Verley (philippe.verley@ird.fr)

with that one:

> please contact Nicolas Barrier (nicolas.barrier@ird.fr)

?
Many thanks.

**Comment by FIN-JBarile** [comment]
@agruss2 Contact info changed. Please check.

**Comment by agruss2** [comment]
@FIN-JBarile Checked; many thanks! I can now close this issue.
