### ISSUE TITLE
Making sure that we obtain as few NAs as possible for the background functional groups

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#142]
@FIN-casey  (CC: @jhpoelen @FIN-JBarile)
The present issue is related to #114.

If you recall, the default value of the 3 following parameters for background functional groups was set to NA in the “fishbase-mapping.csv” file: 
(1) plankton.TL.plk*; 
(2) plankton.size.min.plk*;
(3) plankton.size.max.plk*;

Then, to be able to obtain as few NAs as possible for background functional groups in OS-MOSE configuration files, we decided to implement the following: 
(Let’s say that we are dealing with a background functional group called “cephalopods” and the parameter “trophic level” or “TL”). 
(1) For that “cephalopods” functional group, the UI has identified, say, 20 species.
(2) Before passing information to the API, the UI appends to these 20 species: a number N of species that belong to the genuses, families and orders of the 20 species. 
(3) When the API receives the list of 20 + N species from the UI, it first considers only the 20 species that belong to the “cephalopods” functional group.
-> (i) Case 1: data are available to derive a value for the parameter “TL” for some of the 20 species that belong to the “cephalopods” functional group. In that case, the “data richness” rule described in #59 is applied to derive a parameter estimate for the parameter “TL” for the “cephalopods” functional group.
-> (ii) Case 2: data are not available to derive a value for the parameter “TL” for none of the 20 species that belong to the “cephalopods” functional group. In that case, the API will con-sider the N appended species to see if it can derive a value for the parameter “TL”.
(4) If we have faced Case 2 above, then:
-> Case 1: data are available to derive a value for the parameter “TL” for some of the N ap-pended species. In that case, the “data richness” rule described in #59 is applied to the list of N appended species to derive a parameter estimate for the parameter “TL” for the “cephalo-pods” functional group.
-> (ii) Case 2: data are not available to derive a value for the parameter “TL” for none of the N appended species. In that case, the API will provide the value NA for the parameter “TL” for the “cephalopods” functional group.

What is described above was successfully implemented a few months ago. However, I do not know which value was given to N (the number of appended species). N was set to some specific value (50? 100?), because we did not want to the bridge between FB/SLB and OSMOSE to take an excessively long time to deliver parameters. 

However, today I ran a new test where I queried parameters for the Iceland Shelf/Sea ecosystem; and there was still a non-negligible number of NAs for background functional groups in the OSMOSE configuration files. 

Therefore, I have a simple question for @FIN-casey:  What value did you give to N, the number of appended species? 
Once you have let me know, I will close the present GitHub issue and open a new one, where I will suggest a series of test to find a value for N that yields as few NAs as possible for the parameters for background functional groups without excessively increasing the computation time.

**Comment by agruss2** [comment]
@FIN-casey @FIN-JBarile As discussed with Skit and Deng on Skype a few days ago, I will create a test case for this GitHUb issue and will come back to you then with more details so that we can solve the present issue. Many thanks!

**Comment by FIN-JBarile** [comment]
@agruss2 

The same approach for getting N is applied for both background and focal, as described in [#141](https://github.com/jhpoelen/fb-osmose-bridge/issues/141#issuecomment-370394884).

**Comment by agruss2** [comment]
@QQ-Sortiz @FIN-JBarile 
Thank you very much for your replies and clarifications. 
I am going to close the present issue, because we have unfortunately too little time to run sensitivity tests to determine the optimum number of appended species. However, I may reopen this issue in the future, if time allows.
