### ISSUE TITLE
Modifying some titles in the UI 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#146]
Could you please? 
(1) Replace "Step 2: Reorganize functional groups" with: "Reorganize functional groups"
(2) Replace "Step 3: Order Focal functional groups" with: "Order Focal functional groups"
(3) Replace "Step 4: Order Background functional groups" with: "Order Background functional groups"
(4) Replace "Step 5: Indicate the time step of your OSMOSE model" with: "Indicate the time step of your OSMOSE model"

Many thanks.

**Comment by FIN-JBarile** [comment]
@agruss2 Titles have been modified in the [UI](http://fin-casey.github.io/wizard.html). Is it intentional to leave Step 1 title as is?

Please check. Thanks.

**Comment by agruss2** [comment]
@FIN-JBarile Many thanks for having addressed this issue; I can close it now. 

To answer your question: I did not mention Step 1 in the present issue, because when #147 and #148 will be addressed, all the steps of http://fin-casey.github.io/wizard.html will need to be followed by the user, except Step 1.
