### ISSUE TITLE
Hosting the UI in fishbase.org (1)

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#147]
The bridge between FishBase/SeaLifeBase and OSMOSE should be accessible from the "Information by Country / Island" section of fishbase.org. In that section, one the Tools entitled "OSMOSE data" should allow the user to request OSMOSE data for a combination of a country and FAO area. 
Could you please implement this? 
Implementing this would entail reworking the current version of the UI so that all the steps of http://fin-casey.github.io/wizard.html needs to be followed by the user, except "Step 1: Getting parameter estimates for your OSMOSE model". 
Many thanks!

**Comment by FIN-JBarile** [comment]
@agruss2 Please tell me if I understand this correctly. From FishBase> Information by Country/Island OSMOSE data, after an FAO area is selected, the user will then be directed to the step "Reorganize function groups" in OSMOSE wizard UI. In the background, data from FishBase will be passed to the OSMOSE UI so to speak. 

Or are you asking that the current UI in Github will be reprogrammed such that it resides with the FishBase website?

I have the same questions for #148.

Thanks.

**Comment by agruss2** [comment]
@FIN-JBarile (CC: @Dengaloo )
I would like the current Github UI to be reprogrammed so that it can be hosted in fishbase.org. 
There is already a tool called "Ecopath data" in the "Information by Country / Island" section of fishbase.org. 
I would like you to please add a new tool called "OSMOSE data" in the "Information by Country / Island" section of fishbase.org. 
Here is how this tool should work:
(1) The user selects a Country/Island in the drop-down list. 
(2) The user selects the "OSMOSE data" Tool. 
(3) The user reaches the following page:
![fishbase org 1 _step1_2](https://user-images.githubusercontent.com/16559622/33489716-4b87d3e2-d67a-11e7-82b0-f170f37171da.jpg)
Please note that “United States (contiguous states)” appears here for illustrative purposes. The country name that will actually appear will be that selected by the user in (1). 
(4) Then, the user goes through all the steps of the current Github UI except Step 1. 

Please let me know if something is not clear. 
Many thanks!

**Comment by FIN-JBarile** [comment]
@qq-sortiz Please implement above specs in FishBase and SeaLifeBase.

In FishBase, add as "OSMOSE parameters" after "Ecopath data". "Ecopath data" will be renamed to "Ecopath parameters".

 In SeaLifeBase, add as last item under Tools.

Thanks.

**Comment by FIN-JBarile** [comment]
@agruss2 
Miel had worked on this earlier. Unfortunately though, this is not possible to implement in GitHub pages. GitHub pages don't support back end technology, i.e. It cannot accept and process URL parameters. In this case, it cannot handle the country parameter passed from the FishBase/SeaLifeBase search page. This option will have to be skipped and instead go through Tools only as in #152.

**Comment by agruss2** [comment]
@FIN-JBarile Thanks a lot for having explained this to me in detail! I actually think that having the bridge hosted in one unique place (i.e., in the Tools section) is a simple, desired option. So, let's close the present issue and forget about it.
