### ISSUE TITLE
Hosting the UI in fishbase.org (2)

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#148]
The bridge between FishBase/SeaLifeBase and OSMOSE should also be accessible from the "Information by Ecosystem" section of fishbase.org. In that section, one the Tools entitled "OSMOSE parameters" should allow the user to request OSMOSE parameters for an ecosystem.
Could you please implement this?
Implementing this would entail reworking the current version of the UI so that all the steps of http://fin-casey.github.io/wizard.html needs to be followed by the user, except "Step 1: Getting parameter estimates for your OSMOSE model".
Many thanks!

**Comment by agruss2** [comment]
@FIN-JBarile (CC: @Dengaloo )
I would like the current Github UI to be reprogrammed so that it can be hosted in fishbase.org. 
There is already a tool called "Ecopath parameters" in the "Information by Ecosystem" section of fishbase.org. 
I would like you to please add a new tool called "OSMOSE parameters" in the "Information by Ecosystem" section of fishbase.org. 
Here is how this tool should work:
(1) The user selects an Ecosystem in the drop-down list. 
(2) The user selects the "OSMOSE parameters" Tool. 
(3) Then, the user goes through all the steps of the current Github UI except Step 1. 

Please let me know if something is not clear. 
Many thanks!

**Comment by FIN-JBarile** [comment]
@qq-sortiz Please implement above similar to #147. Add "OSMOSE parameters" after "Ecopath parameters". We need to adjust the items under Info by Ecosystem. Will address separately.

**Comment by FIN-JBarile** [comment]
@agruss2 
Miel had worked on this earlier. Unfortunately though, this is not possible to implement in GitHub pages. GitHub pages don't support back end technology, i.e. It cannot accept and process URL parameters. In this case, it cannot handle the ecosystem parameter passed from the FishBase/SeaLifeBase search page. This option will have to be skipped and instead go through Tools only as in #152.

**Comment by agruss2** [comment]
@FIN-JBarile Thanks a lot for having explained this to me in detail! I actually think that having the bridge hosted in one unique place (i.e., in the Tools section) is a simple, desired option. So, let's close the present issue and forget about it.
