### ISSUE TITLE
Documenting the API code and providing a tutorial

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#149]
(@jhpoelen, please note that this is not an issue that needs to be addressed now. I will let you know when it needs to be addressed. Many thanks once again for all the great things that you have done for this project). 
We need to start thinking about the maintenance of the bridge between FB/SLB and OSMOSE and future improvements in the tool. 
The maintenance of the bridge between FB/SLB and OSMOSE and future improvements in the tool will be under the responsibility of FishBase/SeaLifeBase team and Arnaud Grüss. 
To facilitate the work of FishBase/SeaLifeBase team and Arnaud, all the API code for this project and a tutorial should be made available to them, via GitHub if possible; if the API code and the tutorial were shared via GitHub, then the documentation work should take inspiration from the following GitHub repository: https://github.com/James-Thorson/VAST

**Comment by agruss2** [comment]
@jhpoelen @QQ-Sortiz ( CC: @Dengaloo @FIN-JBarile )

Jorrit - Please let me introduce you to Miel, who has joined Q-quatics (previously: FIN). 
Miel will be in charge of understanding the functioning of the API and documenting it, so that we can modify the API in the future if need be. 
Could you please confirm that all the necessary Java code is currently available in the GitHub repository?
Moreover, could you please let us know where the API is located and give us access to it, and also provide Miel with all the materials he will need to document the API in a tutorial?

Miel - Please start interacting with Jorrit. Ideally, the tutorial should be ready by March, 18th 2018. Would that work for you?

Thanks a lot everyone!

**Comment by jhpoelen** [comment]
The api code is in this repository (i.e. https://github.com/jhpoelen/fb-osmose-bridge/ ). The "wizard" code is available in  http://github.com/fin-casey/fin-casey.github.io . I'd say that any reasonably trained software engineer should be able to find their way around without my help: the tools used are well-documented and defacto industry standard (e.g., maven, jersey, java, travis-ci, and heroku).

**Comment by Dengaloo** [comment]
Hi Jorrit,

Happy 2018 to you and your family and happy to hear you respond to the messages Arnaud is sending us!

Many thanks for the information. Skit and Miel (the Sea Around Us website manager) will be taking care of your code and hopefully will be able to change or update things when needed.

Greetings now from the Philippines, which I will be leaving in a few hours to fly to Paris, then back to Vancouver.

Deng

**Comment by agruss2** [comment]
@QQ-Sortiz 
I postponed the deadline for this issue to April, 15th 2018. Would that work for you?
Once again, thanks a lot for your excellent work on the UI and API.

**Comment by FIN-JBarile** [comment]
@agruss2 Thanks for reconsidering. That would surely work. Miel will do this soon after he is done with issue #165. 

For this, the documentation Miel will do is just for the API code. The tutorial (a user guide?) will be handled by you, correct?

**Comment by agruss2** [comment]
@FIN-JBarile (CC: @QQ-Sortiz)
Many thanks. 
Yes, absolutely, the documentation I am referring to here is only for the API. This documentation will greatly facilitate future changes in the API by the Q-quatics team. I also want to become more familiar with the API myself via the documentation, so as to be able to make changes in the API myself in the future, if need be. 
I am going to start working on the paper on the bridge very soon. You are correct that this paper will very likely be accompanied by either a small tutorial (user guide) which I will wrote or a better Wiki for the present GitHub repository; I will decide what to do at a later point.
Talk very soon and thanks a lot to you guys once again for all the great work that has been accomplished during the past week; this is making my week :)

**Comment by QQ-Sortiz** [comment]
Hello @agruss2,

Started working on the documentation for the API. Thanks

**Comment by agruss2** [comment]
@QQ-Sortiz (CC: @Dengaloo @FIN-JBarile @jhpoelen) Thanks a lot for having started to work on the documentation of Jorrit's work. We want to learn how to use all of Jorrit's developments and tools, so as to be able to fix API issues ourselves in the future, if need be. We also need to make sure to carefully follow Jorrit's advice, e.g., the recommendations provided in #165.  
Many thanks.

**Comment by agruss2** [comment]
@QQ-Sortiz Thanks a lot once again for the draft of documentation you wrote! I will soon review it and provide you with feedback. Meanwhile, I am going to close the present issue, and will reopen it if need be.
