### ISSUE TITLE
Hosting the UI in fishbase.org: Search page > Tools

### ISSUE THREAD

**Issue by FIN-JBarile** [jhpoelen/fb-osmose-bridge#152]
In addition to #147 and #148, "OSMOSE parameters" will also be made available in the Tools section of the FishBase and SeaLifeBase search pages. This access will open the Step 1 page of the UI in  http://fin-casey.github.io/wizard.html.

@qq-sortiz will implement.

**Comment by FIN-JBarile** [comment]
@agruss2 These are currently implemented in [www.fishbase.ca](http://www.fishbase.ca) and [www.sealifebase.ca](http://www.sealifebase.ca).  We will distribute to the mirrors once we're done with the February 2018 mirror updates.

**Comment by agruss2** [comment]
@FIN-JBarile That's great, many thanks! Please let me know once you have distributed to the mirrors. At that time, I will run a test and eventually close the present issue.

**Comment by FIN-JBarile** [comment]
@agruss2 

[www.sealifebase.org](http://www.sealifebase.org) is now in the February 2018 version. 

For www.fishbase.org, we will distribute the update by tomorrow yet. Those updates will take effect depending on the availability of webmasters in the respective mirrors. I would estimate between end of the week and next.  [www.fishbase.ca](http://www.fishbase.ca) though, is already in ver. February 2018.

**Comment by agruss2** [comment]
@FIN-JBarile Thank you very much for having let me know. Please keep me posted. After I have heard from you again, I will run some tests and will then eventually close the present issue.

**Comment by FIN-JBarile** [comment]
@agruss2 www.fishbase.org is now updated to version Feb 2018. Please check OSMOSE placement. Thanks.

**Comment by agruss2** [comment]
@FIN-JBarile I just ran some tests where I queried OSMOSE parameters in fishbase.org and then in sealifebase.org, and everything worked as intended. I can therefore close the present issue. Many thanks for all your work on this!
