### ISSUE TITLE
Adding a "Back" button on top of pages

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#154]
@QQ-Sortiz @FIN-JBarile 
I received some feedback from a user (Nicolas Barrier) today.
The user suggested us to add a "Back buttom" on top of the following pages of the UI: 
"Reorganize functional groups", "Order Focal functional groups", "Order Background functional groups", "Indicate the time step of your OSMOSE model", and "Download configuration files for your OSMOSE model". 

For example, the following should be done with regards to the page "Order Focal functional groups":
![drawing_for_issue_back_button](https://user-images.githubusercontent.com/16559622/36237472-7f70c2f4-11c1-11e8-9dd4-4a2dbe4c5b25.jpg)

Could you please implement this, and let me know when the changes have been done? 
Many thanks!

**Comment by QQ-Sortiz** [comment]
Hello Arnaud,

I added the Back button and also included the Proceed button. The Proceed button can be easily removed if not necessary.

Just a note, for the "Indicate the time step of your OSMOSE model" page, it appears that putting an additional button on the top may look redundant. You may want to check it. Thanks!

**Comment by FIN-JBarile** [comment]
@agruss2 I agree with Miel on his comment. The last two pages of the wizard will no longer expand vertically, and so the second Back button is somewhat an overkill. That's because our assumption for adding the second Back button is to facilitate navigation when lists are long in a given page. If it's something else, then we rest our case :)

**Comment by agruss2** [comment]
@QQ-Sortiz @FIN-JBarile Thanks a lot, those are all excellent ideas! Adding the "Proceed" button on top of pages was a very good call. I also agree agree that removing the "Back" and "Proceed" buttons from the last two pages makes sense. Therefore, please do that and let me know when this is done; I will then close the present issue. Many thanks!

**Comment by QQ-Sortiz** [comment]
@agruss2 It's already implemented yesterday.

**Comment by agruss2** [comment]
@QQ-Sortiz Very nice; many thanks! I am closing the present GitHub issue now, then.
