### ISSUE TITLE
Rename the title of the first page of the UI

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#155]
@QQ-Sortiz @FIN-JBarile 
Could you please rename the title of the first page of the UI? 
I would like "Step 1: Getting parameter estimates for your OSMOSE model" to be replaced with: "Getting parameter estimates for your OSMOSE model".
Many thanks!

**Comment by QQ-Sortiz** [comment]
Updated the title. Kindly check. Thanks!

**Comment by agruss2** [comment]
@QQ-Sortiz Just checked this; many thanks! I can now close the present issue.
