### ISSUE TITLE
Updating the text of UI Page 2

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#156]
@QQ-Sortiz (CC: @FIN-JBarile and @Dengaloo) 
OSMOSE users have decided to rename "background functional groups" into "biotic resources".
We therefore need to update the UI and the files it provides accordingly. 

First, the text of UI Page 2 needs to be updated, as follows:

> FishBase/SealifeBase defined functional groups for you
> 
> Please feel free to:
> 
> (1) Indicate whether each functional group is a focal functional group or a biotic resource, using dedicated radio buttons. 
> 
> (2) Remove species from some functional groups.  
> 
> (3) Redistribute species between functional groups. 
> 
> (4) Remove functional groups from the table. 
> 
> (5) Create functional groups. 
> 
> (6) Rename functional groups. 
> 
> *Caution: The name of the functional groups should not include spaces nor underscores. For example, "SmallPelagics" is a valid functional group name, but not "Small pelagics" nor "Small_pelagics".
> 
> When you are ready, press Proceed to go to the next step.

Many thanks!

**Comment by QQ-Sortiz** [comment]
Changes were implemented. Kindly check.

**Comment by agruss2** [comment]
@QQ-Sortiz 
There is a typo.
Please replace "biotic resources" with: "biotic resource". In other words, remove the "s".
Thanks a lot.

**Comment by QQ-Sortiz** [comment]
You first said that it should be "resources" then on your example, it is just "resource". Anyway, it is now corrected. Thanks

**Comment by agruss2** [comment]
@QQ-Sortiz Many thanks; I can now close the present issue.
