### ISSUE TITLE
Updating the text associated with the first information button of UI Page 2

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#157]
@QQ-Sortiz - Could you please update the text associated with the first information button of UI Page 2 as follows?

> Focal functional groups are groups of species/species which are explicitly considered in OSMOSE (i.e., their whole life cycle is modeled), while biotic resources are groups of species/species (usually having a low trophic level) which are implicitly considered in OSMOSE (fields of biomass for these groups are used to force the OSMOSE model).
> 
> By default, FishBase/SeaLifeBase defined all functional groups as focal functional groups, except the phytoplankton and zooplankton groups; the phytoplankton and zooplankton groups can only be defined as biotic resources.

Many thanks!

**Comment by QQ-Sortiz** [comment]
Changes were implemented. Kindly check.

**Comment by agruss2** [comment]
@QQ-Sortiz You did not make changes correctly. 
There are two places where "background functional groups" needed to be replaced with "biotic resources". Please replace the second instance of "background functional groups" with"biotic resources".
Thanks a lot.

**Comment by QQ-Sortiz** [comment]
Corrected. Thanks

**Comment by agruss2** [comment]
Many thanks; I can now close the present issue.
