### ISSUE TITLE
Updating the text associated with the fifth information button of UI Page 2

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#159]
@QQ-Sortiz Regarding the text associated with the fifth information button of UI Page 2,
could you please replace:
"FOR BACKGROUND FUNCTIONAL GROUPS ONLY"
with:
"FOR BIOTIC RESOURCES ONLY"
?

Many thanks!

**Comment by QQ-Sortiz** [comment]
Changes were implemented. Kindly check.

**Comment by agruss2** [comment]
Thanks a lot; I can now close this issue.
