### ISSUE TITLE
Renaming a column of the table provided in UI Page 2

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#160]
@QQ-Sortiz Regarding the table provided in UI Page 2, 
there is currently a column named "Background Functional Group".
The name of this column should be changed into: "Biotic Resource".
Many thanks!

**Comment by QQ-Sortiz** [comment]
Changes were implemented. Kindly check.

**Comment by agruss2** [comment]
Thanks a lot; I can now close this issue.
