### ISSUE TITLE
Changing some values in the "functional_groups.csv" file provided in "osmose_config.zip"

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#165]
@QQ-Sortiz 
Since we renamed "background functional groups" as "biotic resources", we also need to change some of the values in the "functional_groups.csv" file that is provided in "osmose_config.zip". 

The second column of the "functional_groups.csv" file called "functional group type" currently has two potential values: "focal" and "background".
See for instance the following "functional_groups.csv" file that I obtained after having queried parameters for the Iceland Shelf/Sea ecosystem and having defined the group "cephalopods" as a biotic resource: 
[functional_groups.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/1785474/functional_groups.zip)

--> Could you please make the necessary changes in the API so that, from now on, the potential values of the second column of the "functional_groups.csv" file called "functional group type" are either "focal_functional_group" or "biotic_resource" (instead of "focal" and "background", respectively)?

Many thanks!

**Comment by QQ-Sortiz** [comment]
Hello @agruss2,

I tried to changed the potential values of the functional group type. Kindly check. Thanks.

**Comment by agruss2** [comment]
@QQ-Sortiz 
I just ran a test for the Azores Islands, where I defined "lobstercrab" as a "biotic resource".
However, I still get the values "focal" and "background" in the "functional group type" column of the "functional_groups.csv" file; see: [functional_groups.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/1793666/functional_groups.zip)
--> Could you please make the necessary changes in the API, so that when the API populates the "functional_groups.csv" file, it populates the column entitled "functional group type" with the following values: either "focal_functional_group" or "biotic_resource" (instead of "focal" and "background", respectively). 
Many thanks!

**Comment by QQ-Sortiz** [comment]
Hello @jhpoelen,

I would like to ask something about this issue. I already changed the GroupType values where it gets functional group type for functional_groups.csv. Passed on the building the repo on Travis. Passed on all the tests but still the GroupType.FOCAL and GroupType.BACKGROUND has the same value. Does this one needs resetting of the server or cached? Your help will be much appreciated. Thanks

**Comment by agruss2** [comment]
@jhpoelen 
(CC: @QQ-Sortiz and @FIN-JBarile)
Could you please help Miel here? Miel has done his very best to address this issue, but he is stuck and really needs your insights here since you developed the settings. We are in a transition phase, where Miel is figuring out how everything that you have set up is working. His current work will allow us to get a comprehensive understanding of your settings, which will allow us to make all required changes in the bridge between FB/SLB and OSMOSE ourselves in the near future. 
Many thanks in advance!

**Comment by jhpoelen** [comment]
Please note that changes need to satisfy this issue https://github.com/jhpoelen/fb-osmose-bridge/commit/b686944659dab317ab2cd9e74bc5d047c9859b8a . For future reference, please setup a java development ide and supporting tools before editing this code base.

**Comment by agruss2** [comment]
@jhpoelen Thank you so much for this pro bono work !! This is very much appreciated. I just ran a test for the Iceland/Shelf sea ecosystem, which confirmed that the present issue has been fully solved. 
@QQ-Sortiz (CC: @Dengaloo @FIN-JBarile) Jorrit very kindly solved this issue. Thanks a lot for having started to work on the documentation of Jorrit's work. We want to learn how to use all of Jorrit's developments and tools, so as to be able to fix API issues ourselves in the future, if need be. We also need to make sure to carefully follow Jorrit's advice, including the one above, i.e., "Please note that changes need to satisfy this issue b686944 . For future reference, please setup a java development ide and supporting tools before editing this code base."

Many thanks to you all.
