### ISSUE TITLE
Making sure that the user can deselect functional groups in Step 2 without making the UI freeze

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#168]
@QQ-Sortiz 
Regardless of (1) the web browser I am using and (2) the marine region I am considering (i.e., the marine ecosystem or combination of country/FAO area/state or province I am considering), 
every time I deselect (a) functional group(s) from the table provided in Step 2, the UI freezes. 
I am not sure what is going on. 
I suspect that this is solely a UI issue. Please let me know if this is not correct.
Anyway, please let me know if what I reported here is clear enough and if you could address this important issue as soon as possible.
Many thanks!

**Comment by QQ-Sortiz** [comment]
Fixed issue. Problem is it creates an endless loop when checking for the functional and background groups. Kindly check. Thanks!

**Comment by agruss2** [comment]
I just ran a test and can confirm that this issue has been solved. Therefore, I am going to close the present GitHub issue. Awesome work, many thanks!
