### ISSUE TITLE
No longer defining the zooplankton species as "zooplankton" in the FishBase tables

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#170]
@FIN-JBarile @QQ-Sortiz (CC: @Dengaloo) 
Here is what I would like us to do, please:
(1) We will keep defining generic "phytoplankton" and "zooplankton" groups in Step 2; 
but, in addition:
(2) We will not prevent the web service from defining additional zooplankton groups in Step 2. In other words, relevant FishBase tables should be updated so that the zooplankton species (i.e., _Euphausia lucens_, _Farfantepenaeus duorarum_, etc.) are no longer defined as "zooplankton" in the FishBase tables, so that there is nothing preventing them from appearing in the table provided in Step 2.
All this will also be clarified in the paper on the web service that I am currently writing. 
Please let me know if you have any questions/comments. 
Many thanks!

**Comment by FIN-JBarile** [comment]
@agruss2 We have redone the data source for the UI to accommodate above specifications. 

@QQ-Sortiz will advise when it is applied in the UI.

**Comment by QQ-Sortiz** [comment]
Hello @agruss2 
cc: @Dengaloo 

Uploaded the new json files and was able to create a configuration file for Gulf of Mexico with all the functional groups checked. Kindly check, Thanks!

**Comment by agruss2** [comment]
@QQ-Sortiz @FIN-JBarile @Dengaloo 
I just ran some tests and can confirm that the present issue has been solved; I am, therefore, going to close it. 
Awesome work Skit and Miel, many thanks!
