### ISSUE TITLE
Update the information provided by the fifth information button in UI Step 2

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#171]
@QQ-Sortiz Regarding the last piece of information provided by the fifth information button in UI Step 2 -

Could you please replace:

*Note: To identify relevant Latin names or class names for the new functional group, you can access FishBase/SealifeBase by clicking on the FishBase icon or the SealifeBase icon, which are both located at the top-right hand corner of the table provided below. FishBase provides data for fish, while SealifeBase provides data for all the other types of marine organisms.

with:

*Note 1: To identify relevant Latin names or class names for the new functional group, you can access FishBase/SealifeBase by clicking on the FishBase icon or the SealifeBase icon, which are both located at the top-right hand corner of the table provided below. FishBase provides data for fish, while SealifeBase provides data for all the other types of marine organisms.
*Note 2: A workaround to fill in the “Species” column for a biotic resource you create consists of: (1) temporarily defining the biotic resource as a “Focal Functional Group”; (2) filling in the “Species” column”; and (3) redefining the functional group as a “Biotic Resource”. 

Many thanks!

**Comment by QQ-Sortiz** [comment]
Hello @agruss2,

Updated the fifth information on UI Step 2.

**Comment by agruss2** [comment]
@QQ-Sortiz 
Thanks a lot for having worked on this. 
However, Note 1 and Note should be please provided in two separate paragraphs. 

This is what is currently implemented:

*Note 1: To identify relevant Latin names or class names for the new functional group, you can access FishBase/SealifeBase by clicking on the FishBase icon or the SealifeBase icon, which are both located at the top-right hand corner of the table provided below. FishBase provides data for fish, while SealifeBase provides data for all the other types of marine organisms. *Note 2: A workaround to fill in the “Species” column for a biotic resource you create consists of: (1) temporarily defining the biotic resource as a “Focal Functional Group”; (2) filling in the “Species” column”; and (3) redefining the functional group as a “Biotic Resource”.

And this is what I would like, please:

*Note 1: To identify relevant Latin names or class names for the new functional group, you can access FishBase/SealifeBase by clicking on the FishBase icon or the SealifeBase icon, which are both located at the top-right hand corner of the table provided below. FishBase provides data for fish, while SealifeBase provides data for all the other types of marine organisms. 
*Note 2: A workaround to fill in the “Species” column for a biotic resource you create consists of: (1) temporarily defining the biotic resource as a “Focal Functional Group”; (2) filling in the “Species” column”; and (3) redefining the functional group as a “Biotic Resource”.

Please let me know when you have made the necessary changes. Many thanks!

**Comment by QQ-Sortiz** [comment]
@agruss2 

Seperated Note1 and Note2. Thanks!

**Comment by agruss2** [comment]
@QQ-Sortiz Perfect, many thanks! I can now close this issue.
