### ISSUE TITLE
apparent invalid sealifebase spec code for Tylosurus acus: http://sealifebase.org/summary/acus

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#177]
Steps to reproduce:

1. use Web UI to create a default configuration for Gulf of Mexico
2. download resulting osmose_config.zip (see attached)
3. inspect functional_groups.csv 

expected:
all species in functional groups have valid sealifebase / fishbase summaries.

actual:
on row 317, I found:  

functional group name | functional group type | species name | species url
-- | -- | -- | --
fishreefassociatedlg | focal_functional_group | Tylosurus acus | http://sealifebase.org/summary/acus

note the species url https://sealifebase.org/summary/acus

[osmose_config.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/2342570/osmose_config.10.zip)

**Comment by jhpoelen** [comment]
Please note that other values look ok, e.g., 


functional group name | functional group type | species name | species url
-- | -- | -- | --
fishflatfishsmmd | focal_functional_group | Paralichthys albigutta | http://fishbase.org/summary/980
fishflatfishsmmd | focal_functional_group | Citharichthys macrops | http://fishbase.org/summary/4214
fishflatfishsmmd | focal_functional_group | Achirus lineatus | http://fishbase.org/summary/4256
cephalopods | focal_functional_group | Octopus vulgaris | http://sealifebase.org/summary/58190
cephalopods | focal_functional_group | Thysanoteuthis rhombus | http://sealifebase.org/summary/58136
cephalopods | focal_functional_group | Todarodes sagittatus | http://sealifebase.org/summary/57559
cephalopods | focal_functional_group | Illex coindetii | http://sealifebase.org/summary/58130
cephalopods | focal_functional_group | Illex illecebrosus | http://sealifebase.org/summary/58129

**Comment by jhpoelen** [comment]
The unexpected reference to "http://sealifebase.org/summary/acus" appeared in the request sent from the Web UI ( 
[request-from-UI.json.gz](https://github.com/jhpoelen/fb-osmose-bridge/files/2342584/request-from-UI.json.gz)
) . Also, the reference appears to be the only malformed fishbase/sealifebase species url judging from the result of below

```bash
$ zcat ~/Desktop/request-from-UI.json.gz  | jq .  | grep -P  "base" | grep -P  "summary/([a-z,\"])+$"
          "url": "http://sealifebase.org/summary/acus"
$
```

**Comment by FIN-casey** [comment]
Hello @jhpoelen,

Thank you for pointing this out. I updated the wizard to pass a correct link for this.

**Comment by jhpoelen** [comment]
@FIN-casey thanks! I confirmed that Tylosurus acus acus now points to http://fishbase.org/summary/976 .
