### ISSUE TITLE
Minimum and maximum predator/prey size ratios should not all be set to their default values

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#178]
@jhpoelen To test whether #175 was fulled solved, I ran a test today, where I queried parameter estimates for the Gulf of Mexico for the OSMOSE model of the West Florida Shelf (“OSMOSE-WFS”). 
The majority of the issues we were previously facing were solved, which is really great. However, there are a few issues that remain to be solved, which is why I opened the present GitHub issue. 
We still have two parameters that are set to their default values in the “osm_param-predation.csv” file for all focal functional groups: (i) “predation.predPrey.sizeRatio.max.sp*”, which is set to 3.5 for all focal functional groups; and (ii) “predation.predPrey.sizeRatio.min.sp*”, which is set to 30 for all focal functional groups; please see 
[osmose_config.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/2346316/osmose_config.zip)
However, we filled in the “PredPreyRatioMin” and “PredPreyRatioMax” columns of the FishBase/SeaLifeBase’s table “estimate” for all the species represented in FishBase and SeaLifeBase, so many of the focal functional groups represented in the OSMOSE-WFS model should have minimum and maximum predator/prey size ratios set to a value different from the default values of these two parameters. 
Do you know why this is happening? Could you please check what is going on, attempt to fix the present issue, and then let me know so that I can run a new test with the web application? 
Many thanks!

**Comment by agruss2** [comment]
@FIN-JBarile @QQ-Sortiz (CC: @jhpoelen)
I suspect that the issue mentioned above could be due to an update of the “estimate” FishBase/SeaLifeBase tables in the fishbase_archiver repository. 
Therefore, @FIN-JBarile and @QQ-Sortiz – Could you please let us know if the latest version of the “estimate” FishBase/SeaLifeBase tables in the fishbase_archiver repository include the following columns: “PredPreyRatioMin”, and “PredPreyRatioMax”? 
If not, then the issue mentioned above can be solved by re-uploading a version of “estimate” FishBase/SeaLifeBase tables including the columns “PredPreyRatioMin” and “PredPreyRatioMax”. 
@jhpoelen - Could you please interact with @FIN-JBarile and @QQ-Sortiz so that the present issue can ultimately be solved? 
Many thanks to you all!

**Comment by FIN-JBarile** [comment]
@agruss2 

The estimate tables of FB and SLB that currently in use by the API are supposedly in the [fourth patch of the fishbase_archiver](https://github.com/jhpoelen/fishbase_archiver/releases/tag/v0.2.1-patch4). The PredPreyRatioMin/Max fields are present in each. This is actually a copy of the version from which you verified results for sometime Feb/March.

So we checked the table_names.tsv file in the same patch and found that the estimate table name declared was in the plural form. Miel had corrected that. I ran a quick test and got non-default results for predation.predPrey.sizeRatio.min/max parameters in the predation file. Please verify.

@jhpoelen I hope it's ok that we didn't create a new patch for above correction.

cc @QQ-Sortiz

**Comment by jhpoelen** [comment]
@FIN-JBarile @QQ-Sortiz nice catch! Am eagerly awaiting the test results.

Formally, you'd have to create a new patch with this change, but I am ok with this for now. Perhaps we should consider depositing citable versions of the releases/patches with zenodo.org . This would make immutable copies of the archives for future reference. I'd be happy to help set this up.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @QQ-Sortiz 
I have some great news. I just ran a test where I queried parameter estimates for the Gulf of Mexico for the OSMOSE-WFS model, and I can confirm that the present issue has been solved. Thanks a lot! 
Closing this issue now.
