### ISSUE TITLE
Reconciling Jorrit Poelen's approach and Deng Palomares' approach

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#18]
During the meeting at UBC in March 2015, Deng Palomares mentioned that, to obtain parameter estimates for functional groups, the user would be asked a series of questions (Query wizard). The user would provide the geographical location of his/her OSMOSE model. He/she could then be asked to: (1) provide a list of the functional groups represented in his/her OSMOSE model; (2) indicate the species making up each functional group; (3) identity a reference species for each functional group; (4) indicate whether each functional group is a focal functional group or a background functional group. 
Jorrit Poelen through the bridge between FishBase/SeaLifebase and OSMOSE offers a different approach, allowing the user to define himself/herself the functional groups of his/her OSMOSE model and let the bridge provide parameter values for these functional groups. 
To my mind, Jorrit's approach would suit OSMOSE users better. However, to reconcile Deng's approach and Jorrit's approach, it would be good that the bridge between FishBase/SeaLifebase and OSMOSE searches for parameter values coming as much as possible from the ecosystem represented in the OSMOSE model under consideration. This is important given that two populations of the same species can sometimes have significantly different ecological traits and diet patterns (e.g., different growth patterns due to the temperatures prevailing in the ecosystem where they live).
Moreover, the user should define a reference species for each focal functional group and a few reference species for each background functional group before running the bridge between FishBase/SeaLifebase and OSMOSE. We need to think about how to implement the definition of reference species in OSMOSE configuration files. 
One additional thought, though: In case the bridge provided parameter estimates for the reference species of each focal functional group only, how could we deal with situations where parameters are missing (e.g., the bridge can provide growth and reproduction parameters, etc., but not other parameters (e.g., Q/B) for the reference species defined)?

**Comment by jhpoelen** [comment]
@agruss2 In my mind the Query Wizard approach and current OSMOSE bridge are complementary. The query wizard simply adds user interface layer on top of the existing OSMOSE bridge web service (see [README.md](./README.md)) for usage. 

Suggested next steps: address #8 , allowing to name focal functional groups different from their focal species, and #24 (select ecosystem / stock).

@agruss2 curious to hear your thoughts on this.

**Comment by agruss2** [comment]
@jhpoelen I agree that the Query Wizard approach and current OSMOSE bridge are complementary, and that the query wizard simply adds user interface layer on top of the existing OSMOSE bridge web service. 
See #9: I offered a solution there to define a reference species for each focal functional group. 
I think that, for now, we should focus our efforts on your bridge between FishBase/SeaLifeBase and OSMOSE, and only come back to the issue of the Query Wizard once we are fully satisfied with your bridge. Curious to hear your thoughts on #9.
I am going to address #24 soon.

**Comment by jhpoelen** [comment]
@agruss2 can we close this issue?

**Comment by agruss2** [comment]
@jhpoelen Yes, we can. Going to close it.
