### ISSUE TITLE
Altering the default value of some OSMOSE parameters

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#19]
Currently, in all OSMOSE applications, the maximum annual ingestion rate (Q/B) of all focal functional groups is set to 3.5 g of food per g of individual and per year for all focal functional groups. This is obviously open to criticism (especially from researchers like Daniel Pauly and Deng Palomares!). Therefore, the bridge between FishBase/SeaLifeBase and OSMOSE should provide the user with estimates of maximum annual ingestion rate (Q/B) for the different focal functional groups represented in his/her OSMOSE model. 
Question: Currently, in all OSMOSE applications, the critical predation efficiency of all focal functional groups is set to 0.57, while the maximum starvation mortality of all focal functional groups is set to 0.3 year-1. Could the bridge between FishBase/SeaLifeBase and OSMOSE provide estimates for these two parameters? Should we actually try to make the bridge provide estimates for these two parameters? More generally, should we restrict the number of parameter types for which the bridge between FishBase/SeaLifeBase and OSMOSE provide estimates?

**Comment by jhpoelen** [comment]
@agruss2 would it be an idea to split this into two separate issues: one about populating maximum annual ingestion rate (Q/B) and a separate one about critical predation efficiency. I think that a separation of concerns will help us progress more quickly.

**Comment by agruss2** [comment]
@jhpoelen The first paragraph is a comment; it therefore belongs to the wiki. The second paragraph is an issue. We could: (1) move the first paragraph to the osmose wiki; (2) create a new issue for the second paragraph; and (3) close the current issue. What do you think?

**Comment by jhpoelen** [comment]
Sounds like a good plan to me!

**Comment by agruss2** [comment]
Nice. Could you please do it?

**Comment by jhpoelen** [comment]
I'd be happy to do it, although, moving forward, the idea is to get into the habit of managing issues and documentation as a group. In addition, I should probably not be the person writing OSMOSE documentation, given my limited exposure with OSMOSE.

**Comment by jhpoelen** [comment]
for new issue see https://github.com/jhpoelen/fb-osmose-bridge/issues/25

**Comment by agruss2** [comment]
I agree. Will do it next time :smiley: 
I will work on the OSMOSE documentation.

**Comment by jhpoelen** [comment]
see https://github.com/jhpoelen/fb-osmose-bridge/wiki/OSMOSE#ingestion-rate .
