### ISSUE TITLE
allow for generation of a functional group using fishbase fields

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#2]
Currently, functional group definitions are static. In the future, we'd like to be able to generate configuration for new functional groups using existing open data sources such as fishbase and sealifebase.

**Comment by jhpoelen** [comment]
@agruss2 I've added you to the collaborators of this code repository. This means that you can now edit the fishbase mapping file at https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv . Please please add all the osmose parameters that you'd like to "bridge" to fishbase/sealifebase. Once that is done, I'll take a stab at building the individual bridges and populate the appropriate Osmose parameters.

**Comment by agruss2** [comment]
@jhpoelen I have done my best, but some parameters are missing. 
What would help would be to get a clue about the meaning of what each "column_name" of a given "table" (e.g., popgrowth) exactly means. I have tried to figure this out on fishbaseapi, but have not managed to. I am going to send Deng an mean. 
One last note: This time I made commits directly in the "master" folder, but in the future I will probably make commits in a "clean_up" directory and let you decide if you want to merge it with the "master" folder.

**Comment by jhpoelen** [comment]
hi @agruss2 I don't mind if you keep adding the mapping to the master branch: all versions are retained, and we can always revert if we need to. However, if you want to be more careful, you might want to consider creating a "pull request". This is a git way to request a change to be included in a branch. I'd be happy to help you walk through this and perhaps create some specific step-by-step documentation for this for reference.

**Comment by jhpoelen** [comment]
Closing issue as functional groups can now be generated using the steps documented at https://github.com/jhpoelen/fb-osmose-bridge . Please document bugs, or enhancement is separate issues.
