### ISSUE TITLE
Estimating accessibility coefficients and theoretical accessibility coefficients for OSMOSE

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#20]
During the meeting at UBC in March 2015, it was discussed that “accessibility coefficients” and “theoretical accessibility coefficients” could be decomposed into multiplicative components. 
● In almost all OSMOSE applications, accessibility coefficients are set to 0.8 for all life stages of focal functional groups. This is not the case in the OSMOSE-WFS model. 
We would like to express accessibility coefficients as: accessibility coefficient = 0.8_coeff_1_coeff_2, where coeff_1 reflects the degree of overlap between functional groups in the water column; and coeff_2 reflects the chances of a given life stage of a given functional group to be eaten by other functional groups based on its morphology, swimming ability, toxicity, spineness, etc. 
Coeff_1 would take the following values: (i) 1 (strong overlap in the water column); (ii) 0.5 (moderate overlap in the water column); or (iii) 0.125 (small overlap in the water column). Coeff_1 can be inferred from the maximum and minimum depth fields or the common depth fields entered in FishBase/SeaLifeBase. 
Coeff_2 would be set to either 0 or 1. The idea here would be to set coeff_2 to 0 only if there is strong evidence that a life stage of a given functional group cannot be consumed by another one. The rationale here is that we want to remain within the spirit of the OSMOSE modeling approach, where diet compositions emerge from model simulations, essentially based on the degree of spatial overlap between functional groups and their predator/prey size ratios. 
● Theoretical accessibility coefficients are usually set to 0 or 1. Currently, in the OSMOSE-WFS model, theoretical accessibility coefficients take the following values: 0, 0.1, 0.4, 0.8 or 1. Remember that the accessibility coefficients of background functional groups are given by the product of: (i) their availability to all focal functional groups (estimated during the calibration process); and (ii) their theoretical accessibility coefficients. 
We would like to express theoretical accessibility coefficients as: theoretical accessibility coefficient = coeff_1*coeff_2, where coeff_1 reflects the degree of overlap between the background functional group and focal functional groups in the water column. Coeff_1 can be inferred from the maximum and minimum depth fields or the common depth fields entered in FishBase/SeaLifeBase.
Coeff_2 is a binary variable (0 or 1) reflecting whether the background functional group should be consumed by the different focal functional groups or not, based on available evidence. 
Coeff_2 should be parameterized based on insights from the GoMexSI database and other information.

What are your thoughts about the above? 
Obviously, the implementation of the computation of the accessibility coefficients and theoretical accessibility coefficients for OSMOSE through the bridge between FishBase/SeaLifeBase and OSMOSE will require a lot of additional reflection ...

**Comment by jhpoelen** [comment]
@agruss2 as far as I can tell, the water column coefficient (coef_1) should be pretty easy to calculate using the depth traits. Coef_2 can be easily derived from trophic data using a GoMexSI (or perhaps GloBI) query to list all interactions between the two taxa (species/lifestages or perhaps genus/family level queries) that are being compared. Until we have a good handle on these queries (should be easy when we choose to use GloBI e.g. [What amphipods (Amphipoda) do hardhead catfish (_Ariopsis felis_) eat?] (http://api.globalbioticinteractions.org/interaction?sourceTaxon=Ariopsis%20felis&targetTaxon=Amphipoda&interactionType=eats&type=csv)), we can set coef_2 to 1. With this approach, we can gradually make the parameters more dynamic.

**Comment by agruss2** [comment]
@jhpoelen I agree that the water column coefficients (coef_1's parameters) will be pretty easy to calculate from FishBase tables. 
Regarding Coef_2, it is wise to set it to 1 for now. I am still unclear about the best and most objective way to parameterize Coef_2's parameters and this is something we should discuss with the group.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @Dengaloo
We need to have a phone call soon so as to determine how accessibility coefficients and theoretical accessibility coefficients could be estimated using the bridge between FishBase/SeaLifeBase and OSMOSE. 
WIth respect to coeff_2: I have no idea yet how we could estimate this coefficient using the bridge between FishBase/SeaLifeBase and OSMOSE. 

WIth respect to coeff_1 (Water column coefficient): There is a bunch of FishBase fields we coul use to get this coefficient, including among others: (1) the "Benthic", "Demersal" and "Pelagic" fields in FishBase's ecology.csv; and (2) the "DepthMin" and "DepthMax" fields in FishBase's estimatedepth.csv. I would like to make the best use FishBase fields to estimate coeff_1's. For instance, in the West Florida Shelf ecosystem, large crabs are benthic, while anchovies and siversides are pelagic. However, anchovies and siversides spend some time close to the bottom, such that they constitute a fraction of the diet of large crabs. Therefore, the accessibility coefficient of anchovies/silversides to large crabs cannot be set to 0.1; it would be pertinent instead to set the accessibility coefficient of anchovies/silversides to large crabs to, say, 0.1. I would like to find the best way to implement this kind of computations with the bridge between FishBase/SeaLifeBase and OSMOSE.

**Comment by agruss2** [comment]
@Dengaloo 
I am going to extend the deadline for #32, because we are going to need some time to derive predictive models for min. and max. predator/prey size ratios from all the data that I shared with you. 
While we are working on the models for min. and max. predator/prey size ratios, let's address the present issue that pertains to the estimation of accessibility coefficients and theoretical accessibility coefficients for OSMOSE models.

**Comment by Dengaloo** [comment]
@agruss2 we need to discuss this further. not all species will have the necessary parameters, we would need to fill in some of these parameters, e.g., depths, from the ecology of the species (we already have this in the Estimates table, i.e., depth proxy if min or max depth is not available). But, we would have to agree that this would be OK to do.

**Comment by agruss2** [comment]
@Dengaloo I think that it would be better to keep things simple here, since OSMOSE modelers usually want the diet compositions emerging from OSMOSE simulations to be primarily determined by predator/prey size ratios and the distribution of functional groups in the horizontal dimension (the latter being determined by distribution maps). Here is what I am offering:
(1) We calculate both the accessibility coefficients and the theoretical accessibility coefficients as:
accessibility coefficient = 0.8* coeff_1
where coeff_1 reflects the degree of overlap between functional groups/life stages of functional groups in the water column. Coeff_1 can take the following values: (i) 1 (strong overlap in the water column); (ii) 0.5 (moderate overlap in the water column); or (iii) 0.125 (small overlap in the water column). Coeff_1 can be inferred from relevant FishBase/SeaLifeBase fields (see below). 
(2) In the README file that is provided in the “osmose_config” zip file by the bridge, we mention to the user that: (i) the calculation of the accessibility coefficients and theoretical accessibility coefficients was based solely on the degree of spatial overlap between functional groups in the water column; and (ii) the user should feel free to set some of the accessibility coefficients and theoretical accessibility coefficients provided by the bridge to 0, if they are aware of papers/reports/evidence showing that a given functional group/life stage of a functional group cannot be consumed by another  functional group/life stage of a functional group. 
Do you like these ideas? 
Now, there is a bunch of FishBase fields that we could use to get an estimate coeff_1, including among others: (1) the "Benthic", "Demersal" and "Pelagic" fields in FishBase's ecology.csv; and (2) the "DepthMin" and "DepthMax" fields in FishBase's estimatedepth.csv. I would like to make the best use of FishBase fields to estimate coeff_1's.
Please let me know what you think, and if you need to discuss all this further on Skype at some point.

**Comment by Dengaloo** [comment]
@agruss2 : I like that idea. So, here is how I think it can work: 1) we see if the functional group in question belongs to the habitat fields (benthic, demersal, pelagic - note that pelagic has also pelagic neritic, pelagic oceanic, etc.); then we test the depth ranges. We can then make a matrix of responses, i.e., if species/functional group has same (1), and same (2), then that is total overlap, coeff_1=1, if same (1) but not same (2), or if not same (1) and same (2), then coeff_1=0.5; if not same (1) and not same (2) then coeff_1=0. Is this something you would like to implement?

**Comment by agruss2** [comment]
@Dengaloo I think that what you propose is excellent overall. 
However, as I mentioned above, I think that it would be better to avoid setting coeff_1 to 0. Indeed, for example, in the West Florida Shelf ecosystem, large crabs are benthic, while anchovies and siversides are pelagic. However, anchovies and siversides spend some time close to the bottom, such that they make up a fraction of the diet of large crabs. Therefore, the accessibility coefficient of anchovies/silversides to large crabs cannot be set to 0; it would be pertinent instead to set the accessibility coefficient of anchovies/silversides to large crabs to, say, 0.1. 
Thus, I would rewrite what you wrote above as follows: "First, we see if the functional group in question belongs to the habitat fields (benthic, demersal, pelagic - note that pelagic has also pelagic neritic, pelagic oceanic, etc.); then we test the depth ranges. We can then make a matrix of responses, i.e., if species/functional group has same (1), and same (2), then that is total overlap, coeff_1=1, if same (1) but not same (2), or if not same (1) and same (2), then coeff_1=0.5; if not same (1) and not same (2) then coeff_1=0.1."
Anyway, I think that we are now clear how to get estimates for accessibility coefficients and theoretical accessibility coefficients. I am planning to write several issues for Jorrit at the end of this week, so that he can improve the API a little bit; and one of these issues will pertain to the estimation of  accessibility coefficients and theoretical accessibility coefficients by the bridge.

**Comment by Dengaloo** [comment]
@agruss2 all good.
