### ISSUE TITLE
The issue of body lengths in OSMOSE

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#22]
OSMOSE applications typically ignore the nature of the length information that they use, i.e., whether this length information pertains to total length (TL), or standard length (SL), or fork length (FL), etc. 
However, the nature of the length information that OSMOSE applications use matters for many reasons including, among other things, the fact that predation in OSMOSE is determined by predator/prey size ratios. 
For this reason, in the OSMOSE-WFS model, the length information provided to the model that does not pertain to TL is converted so that all the length information used by OSMOSE-WFS at run time pertains to TL. I won't detail the code that implement this here. What is important to know is that the changes that I introduced in OSMOSE Java code so that all the length information used by OSMOSE-WFS at run time pertains to TL necessitated the introduction of a new parameter for each focal functional group, "species.length2weight.fl.sp", The "species.length2weight.fl.sp" parameters are boolean variables that determine if the length-weight relationships provided in the "osm_param-species" configuration file were estimated for total lengths (TLs). Even though the "species.length2weight.fl.sp" parameters were integrated into the "osm_param-species" configuration file for the OSMOSE-WFS model, they will undoubtedly be useful for other OSMOSE applications. This parameter could easily be obtained from queries in FishBase/SeaLifeBase to my mind. 
Moreover, the length at infinity (Linf) of some of the functional groups that were provided in the    "osm_param-species" file were initially Linf that were not in total length (TL). All the Linf that were not in TL were converted into Linf in TL using specific relationships between SL and TL and between FL and TL before being entered in the  "osm_param-species" configuration file. 

All this to say that the bridge between FishBase/SeaLifeBase and OSMOSE should check whether the length information about to be provided to OSMOSE pertains to TL or not and, if it is not the case, should transform the length information (i.e., the value of some Linf), using specific relationships from the literature. 
Here is what Deng Palomares mentioned on this issue in October 2015: "With regards to length parameters – Standard length (SL) is available for pretty much all the length parameters entered in Fishbase/SeaLifeBase. Length parameters/length estimates pertaining to SL can be converted into length parameters/length estimates pertaining to TL, using conversion factors from FishBase/SeaLifeBase’s Length-Length table". 
We need to touch base on this issue to make sure that the bridge between FishBase/SeaLifeBase and OSMOSE provides correct length information to OSMOSE for all functional groups.

**Comment by jhpoelen** [comment]
@agruss2 ok, this should pretty straight forward to implement, provided that the length-length table is publicly available through https://fishbase.ropensci.org . Let me know when you are ready to move forward on this.

**Comment by agruss2** [comment]
@jhpoelen I agree that it should not be too difficult to address the present issue. I am ready to move forward on this. Please let me know how you would like to proceed. 
I am now going to close this issue and move some of its text to the wiki
