### ISSUE TITLE
add ability to select an ecosystem / stock 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#24]
Currently, the OSMOSE bridge allows for specifying focal species by scientific name. However, in discussions (e.g. #18) a desire was expressed to include the ecosystem for which the species traits should be extracted. This is important because, if I understand it correctly, species traits vary across ecosystems, even for individual species.

**Comment by agruss2** [comment]
@jhpoelen I think that, for now, we should focus our efforts on your bridge between FishBase/SeaLifeBase and OSMOSE, and come back to the issue of the ecosystem under consideration only when we are satisfied with the functioning of your bridge. See #18 for more details.
