### ISSUE TITLE
Reference species are also needed for background functional groups

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#26]
(The present issue is related to #9)
With respect to background functional groups, four types of parameters can be obtained through the bridge between FishBase/SeaLifeBase and OSMOSE:
(1) Trophic level; 
(2) Minimum size of the background functional group;
(3) Maximum size of the background functional group; 
(4) Theoretical accessibility coefficients of background functional groups to the life stages of focal functional groups. 
The "osm_param-ltl.csv" file indicates the names of background functional groups using the "plankton.name.plk" keys. For instance, The "plankton.name.plk7" key is associated with the "Bivalves" value.
I suggest that, for each focal functional group, we introduce new keys in the "osm_param-ltl.csv" file, which we would call "plankton.reference*.name.plk". For instance, we could introduce several new keys for "Bivalves", one of which could be "plankton.reference1.name.plk" associated with the value "ArgopectenGibbus" (calico scallop).
It will be tricky to define reference species (i.e., latin names) for many focal functional groups, whose constituents are described using genuses or broader taxonomic classifications. For example, in the case of the West Florida Shelf application of OSMOSE, it is indicated that the constituents of the "Small copepods" background functional group are Paracalanidae spp., Oncaea sp., and Oithona sp.
@jhpoelen Please let me know what you think about the above. If you like the ideas mentioned above, I can provide you with an updated version of the "osm_param-ltl.csv" file, for the West Florida Shelf case study, so that you can test the bridge between FishBase/SeaLifeBase and OSMOSE with this new version of the file.

**Comment by agruss2** [comment]
Please have a look at #31, which is related to the current issue.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @Dengaloo
In the "osm_param-ltl.csv" OSMOSE configuration file, I introduced new keys called "plankton.reference.name.plk". For instance, for bivalves (plankton.name.plk7 = "Bivalves"), plankton.reference.name1.plk7 is Argopecten and plankton.reference.name2.plk7 is Donax. 
The new version of the "osm_param-ltl.csv" OSMOSE configuration file can be found in Dropbox in the "OSMOSE configuration files" folder.
You will notice that all the reference species provided in the "osm_param-ltl.csv" are Latin genus names, or family names, or classes, etc. This is because for many background functional groups (e.g., small phytoplankton, meiofauna), it is extremely difficult to find Latin species names. 
Therefore, I trust that we can implement something smart such that FishBase/SeaLifeBase identifies whether the value provided to a given "plankton.reference.name.plk" key is a Latin name, a family name, a class name, etc. to deliver the parameter estimates that we need (i.e., minimum and maximum size of the background functional groups, etc.).

**Comment by jhpoelen** [comment]
@agruss2 rather than using latin names, I would suggest to use a fishbase spec code (or any other taxon id) in addition to providing the taxon name. This help to resolve the issue of figuring out the taxonomic rank of the taxon, 'because we can simply look it up by a taxon code.

**Comment by jhpoelen** [comment]
@agruss2 this can/should also be applied to any other location where taxon names are used. I am almost inclined to make the latin names optional (for humans) and the codes mandatory (machine readable, necessary for trait extraction).

**Comment by agruss2** [comment]
@jhpoelen Please haev a look at #34 and let me know your thoughts.
