### ISSUE TITLE
create diagram / schema/ flowchart on wiki that describes the two bridges

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#28]
GoMexSI > Fishbase

Fishbase > OSMOSE

**Comment by jhpoelen** [comment]
@agruss2 I've added a diagram here: https://github.com/jhpoelen/fb-osmose-bridge/wiki#process . Please let me know what you think. I've attempted to make the email bridges explciit.

**Comment by agruss2** [comment]
Very nice job. We can modify this schema as the project moves along
