### ISSUE TITLE
Skit to publish mysql script that transforms GoMexSI into Fishbase

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#29]
as decided by Deng, Jim, Arnaud, Jorrit on 14-Mar-2016.

**Comment by agruss2** [comment]
@FIN-JBarile Any update on this?

**Comment by agruss2** [comment]
@FIN-JBarile Any update on this?

**Comment by agruss2** [comment]
@FIN-JBarile Any update on this?

**Comment by agruss2** [comment]
The present issue pertains to the bridge between GoMexSI and FishBase/SeaLifeBase and should not appear in this GitHub repository to my mind. Therefore, I am closing the present issue.
