### ISSUE TITLE
Discussion about the species.length2weight.fl.sp parameters

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#30]
The species.length2weight.fl.sp parameters are boolean parameters that determine whether the length-weight relationship of the different focal functional groups represented in an OSMOSE model was estimated using fork lengths (FLs) (as opposed to total lengths (TLs); "true" in the former case and "false" in the latter case). The species.length2weight.fl.sp parameters are parameters that I created for the OSMOSE model of the West Florida Shelf ("OSMOSE-WFS model"), but which will undoubtedly be useful for other OSMOSE applications. This parameter can easily be obtained from queries in FishBase/SeaLifeBase. I think that all that the bridge between FishBase/SeaLifeBase and OSMOSE has to do to determine the species.length2weight.fl.sp parameter of each focal functional group is to look at the value of the "Type" column in FishBase's poplw.csv file and set the value of the species.length2weight.fl.sp parameter to "true" or "false" accordingly; "Type" in FishBase's poplw.csv file is the "type of length measurement used". 

Thought 1 
The Java code of the OSMOSE-WFS model works as follows: (1) OSMOSE reads the species.length2weight.fl.sp parameters; (2) if for a given focal functional group, species.length2weight.fl.sp = true, then a specific equation is used by OSMOSE to convert the TLs of the individuals of the focal functional group into FLs before calculating the body weight of these individuals; otherwise, OSMOSE calculate the weight of the individuals of the functional group using TLs. 
Currently, OSMOSE-WFS uses the linear empirical relationships of Booth & Isted (1997), based on panga (Pterogymnus laniarus) to calculate FL from TL : FL = 0.901.TL + 0.6848. 
Instead of relying on this relationship for one specific species (panga), we could: (1) define two new types of parameters in the "osm_param-species.csv" OSMOSE configuration file (called, e.g., species.aFL.sp and species.bFL.sp) to allow OSMOSE to estimate FL from TL for each focal functional group for which species.length2weight.fl.sp is true as follows: FL = aFL.TL + bFL; and (2) get estimates for the two new parameters (called, e.g., species.aFL.sp and species.bFL.sp) through the bridge between FishBase/SeaLifeBase and OSMOSE. 
Please let me know if you like this idea. If so, then, I will add two rows to the "fishbase-mapping.csv" file. 

Thought 2
There may be some focal functional groups for which no length-weight relationship was estimated using TLs or FLs, and for which only length-weight relationships estimated using standard lengths (SLs) or other types of body lengths are available. 
Therefore, it may be useful to introduce new parameters in the "osm_param-species.csv" OSMOSE configuration file. For example, we may want to introduce the following three types of parameters to acknowledge for the fact that, for some functional groups, available length-weight relationship were not estimated using TLs or FLs, but rather using SLs: (1) species.length2weight.sl.sp; (2) species.aSL.sp; and (3) species.bSL.sp. 
Please let me know what you think. Depending on what you think, I may add a few additional rows to the "fishbase-mapping.csv" file.

**Comment by jhpoelen** [comment]
@agruss2 both thoughts sounds good to me as long as it helps your efforts in improving the bridge. Factoring out the coefficients would make the bridge more versatile, I'd say. Also, I am curious how important this improvement is in relation to the other open items.

**Comment by agruss2** [comment]
@FIN-casey @Dengaloo @FIN-JBarile @jhpoelen 
To further reduce the burden on the development side, I am going to remove this task from our plan. 
The "species.length2weight.fl.sp" parameters are parameters that I created for the OSMOSE model of the West Florida Shelf ("OSMOSE-WFS model") and that are not used in any other OSMOSE applications. Therefore, it makes sense not to bother with these parameters in our project. 
I am going to: (1) close the present issue; and (2) remove the "species.length2weight.fl.sp" parameters from the "fishbase-mapping.csv" file.
