### ISSUE TITLE
Estimating the minimum and maximum body sizes of background functional groups

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#31]
(The present issue is related to #26) 
@FIN-JBarile @Dengaloo
With respect to background functional groups, four types of parameters can be obtained through the bridge between FishBase/SeaLifeBase and OSMOSE:
(1) Trophic level;
(2) Minimum size of the background functional group;
(3) Maximum size of the background functional group;
(4) Theoretical accessibility coefficients of background functional groups to the life stages of focal functional groups.

With respect to the minimum size of the background functional group:
(1) As you know, in the "osm_param-ltl.csv" OSMOSE configuration file, I will soon define a handful of reference species for each background functional group;
(2) My idea is that we will obtain the minimum size of all the reference species for the background functional group through the bridge between FishBase/SeaLifeBase and OSMOSE, simply by extracting LenghMin parameters from the "popll" table; 
(3) Then, a minimum size will be defined for the background functional group as the minimum over all the minimum sizes of reference species. 

With respect to the maximum size of the background functional group:
(1) As you know, in the "osm_param-ltl.csv" OSMOSE configuration file, I will soon define a handful of reference species for each background functional group;
(2) My idea is that we will obtain the maximum size of all the reference species for the background functional group through the bridge between FishBase/SeaLifeBase and OSMOSE, simply by extracting LenghMax parameters from the "popll" table; 
(3) Then, a maximum size will be defined for the background functional group as the maximum over all the maximum sizes of reference species. 

Are you satisfied by this? Or should the minimum and maximum body sizes of background functional groups be estimated using the bridge between FishBase/SeaLifeBase and OSMOSE in another way?

**Comment by Dengaloo** [comment]
For minimum and maximum lengths of background functional groups: as suggested by Arnaud is good. However, I have one concern: what if the composition of the background functional group is so homogenous that the min and max lengths are too similar?

**Comment by agruss2** [comment]
@Dengaloo I do not think that we will run through that issue, but here is what I suggest: we implement this as described above, run a few tests, and figure out whether, for some background functional groups, we end up with min. and max. lengths that are too similar; and, if this is the case, we think about an alternative way to obtain min. and max. length estimates. What do you think?

**Comment by Dengaloo** [comment]
@agruss2 : OK agreed. we go for implementation now then?

**Comment by agruss2** [comment]
@Dengaloo Actually, this is already implemented by the bridge currently (though only for individual species, since the bridge does not work with a list of species to define a functional group yet); and the estimates that the bridge provided the last time that I ran a test were excellent. 
Therefore, I would like to close the present issue. Would you be OK with that? Thanks.

**Comment by Dengaloo** [comment]
@agruss2 : yes go ahead and close it.
