### ISSUE TITLE
create a way to save and share osmose configuration generated by fb-osmose bridge

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#35]
related to #34 - 

Suggested give a user a way to save and re-use a osmose configuration.

Use case:

1. User A shares a osmose configuration X on a website like http://osmose.org/library
2. User B selects a osmose configuration X on a website like http://osmose.org/library
3. User B uses the configuration X to run an osmose configuration

**Comment by agruss2** [comment]
@jhpoelen 
To my mind, the user should only provide only three types of information to the bridge between FishBase/SeaLifeBase and OSMOSE: (1) Information about focal functional groups; (2) information about background functional groups; and (3) the number of time steps per year in their OSMOSE model. 
Once the bridge between FishBase/SeaLifeBase and OSMOSE has run, the user will get a zip file containing: (1) all the OSMOSE configuration files; and (2) a README file detailing which parameter estimates were obtained through the bridge between FishBase/SeaLifeBase and OSMOSE and which parameter estimates remain to be entered by the user.

**Comment by Dengaloo** [comment]
This works in the case that the user accepts configuration X. Will the user be allowed to change configuration X?
