### ISSUE TITLE
Use the FishBase API to populate data in the Wizard that are based on FishBase

### ISSUE THREAD

**Issue by FIN-JBarile** [jhpoelen/fb-osmose-bridge#36]
@FIN-casey will implement this in Step 1 of the Wizard as starting point. Skit will provide guidance on data tables and queries to use. (https://fishbase.ropensci.org)

**Comment by FIN-casey** [comment]
Other data tables are not available in ropensci. Other tables needed are ecosystemref, country subref, countfaoref, and estimate.

The only option connected in the fishbaseapi is the Country dropdown in Step1 of the UI. Ecosystem and FAO are static.

**Comment by agruss2** [comment]
@FIN-casey:
@FIN-JBarile  let me know that she has received the completed list of sub-countries with corresponding FAO areas from @Dengaloo. 
Please solve this issue accordingly. Thanks a lot.

**Comment by agruss2** [comment]
@FIN-casey 
I am having a look at the wizard now, and it seems that what was needed has been implemented. Do you confirm this? 
If this issue has been solved, could you please close it? 
Many thanks for everything.
