### ISSUE TITLE
Assess further which framework will be used for the implementation of the Wizard

### ISSUE THREAD

**Issue by FIN-JBarile** [jhpoelen/fb-osmose-bridge#37]
Frameworks identified that can be used are AngularJS (https://angularjs.org), BackBone.js (http://backbonejs.org) and bare JavaScript.

Step 1 of the Wizard will be implemented using each of the above frameworks to determine which is most appropriate.

@FIN-casey

**Comment by FIN-casey** [comment]
It is decided to use bare JavaScript, with the help of JQuery library.
