### ISSUE TITLE
UI Step 3 after having chosen the option “Define functional groups for me” - Issue no. 5

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#51]
If a user cannot find a species name, the user is instructed to go to a specific fishbase webpage to get more information or provide feedback.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @FIN-casey 
Also, if the user enters of species name that does not exist (or is not available in FishBase/SeaLifeBase) and the error message "Can't find the species" appears, then the species name entered by the user SHOULD NOT APPEAR in the "Species Column".

**Comment by FIN-casey** [comment]
I modified the error message. It is now 
"Can't find the species! 
Please go to fishbase.org to find alternative matches."

**Comment by agruss2** [comment]
This issue has been fully addressed and can therefore be closed.
