### ISSUE TITLE
Move help information from configuration wizard to wiki pages

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#52]
as discussed, we'd like to move help information related to a dedicated page on the wiki: 

http://github.com/jhpoelen/fb-osmose-bridge/wiki 

Then, a help button on the configuration wizard would point to the appropriate wiki page.

**Comment by agruss2** [comment]
@jhpoelen 
I'd prefer the use of "information buttons" as explained in #56

**Comment by agruss2** [comment]
On August, 15th 2016, we agreed to use the "information buttons" option rather than "Wiki' option. Therefore, the present issue can be closed.
