### ISSUE TITLE
Improve the input parameters for the configuration generation tool

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#58]

**Comment by agruss2** [comment]
@jhpoelen 
Jorrit, 
To increase the applicability of the current configuration generation tool, I suggest that you work with some multi-species functional groups from now on. So far, the configuration generation tool has been used to define parameter values for single species only. 
Here are three  functional groups you could work with from now on:
(1) King mackerel ("KingMackerel"): King mackerel (Scomberomorus cavalla); 
(2) Amberjacks ("Amberjacks"): Greater amberjack (Seriola dumerili), banded rudderfish (Seriola zonata), and lesser amberjack (Seriola fasciata); 
and 
(3) Sardine-herring-scad complex ("SardineHerringScad"): Scaled sardine (Harengula jaguana), Spanish sardine (Sardinella aurita), Atlantic thread herring (Opisthonema oglinum), and round scad
(Decapterus punctatus). 

Would you like me to send you the list of all the species making up the different focal and background functional groups represented in my OSMOSE model for the West Florida Shelf? 

Also, do you think that it would be worse considering a background functional group in your current configuration generation tool to increase the applicability of the tool? I would say that this would be a good idea.

**Comment by jhpoelen** [comment]
Hey @agruss2 - sounds like a good plan. Hoping to work on this before out next meeting . . .

**Comment by agruss2** [comment]
@jhpoelen 
I compiled a spreadsheet listing all the species making up the functional groups considered in the OSMOSE model of the West Florida Shelf ("OSMOSE-WFS"). I uploaded this spreadsheet to our shared Dropbox folder (have a look at "RESTORE Act project/OSMOSE material"); it is also attached here. 
[Functional groups considered in OSMOSE-WFS.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/428083/Functional.groups.considered.in.OSMOSE-WFS.xlsx)

Here are three functional groups you could work with from now on:
(1) Amberjacks ("Amberjacks"): Greater amberjack (Seriola dumerili), banded rudderfish (Seriola zonata), and lesser amberjack (Seriola fasciata);
(2) Sardine-herring-scad complex ("SardineHerringScad"): Scaled sardine (Harengula jaguana), Spanish sardine (Sardinella aurita), Atlantic thread herring (Opisthonema oglinum), and round scad
(Decapterus punctatus); 
and 
(3) Echinoderms and large gastropods ("EchinodermsLargeGastropods"): Asteroidea, Echinoidea, Gastropoda, and Holothuroidea. 

What do you think?

**Comment by jhpoelen** [comment]
I've implemented a first pass at a method to define focal groups using a list of species. Currently, traits included in a winner-takes-all approach: if trait A is available for the first species, then trait A will not be considered for the second or any other species. However, if first species does not have trait B, but the second one does, the value for trait B from second species is included.

**Comment by jhpoelen** [comment]
Please see readme at https://github.com/jhpoelen/fb-osmose-bridge for example.

**Comment by jhpoelen** [comment]
@FIN-casey please see the example in readme (see above) for example of POST method to generate osmose configuration.

**Comment by agruss2** [comment]
@jhpoelen 
Looks very good. Could you please provide a demo during our next Skype meeting (i.e., on August, 29th)?

**Comment by jhpoelen** [comment]
@agruss2 glad you like it. I'd be happy to demo this.

**Comment by agruss2** [comment]
@jhpoelen Should this issue be closed or is there something left to address here?

**Comment by FIN-casey** [comment]
Currently, I am getting an error in sending a POST request to the service.
![image](https://cloud.githubusercontent.com/assets/18322815/18270580/3c3afde2-7460-11e6-8cf5-9601f38d4d7d.png)

Below is the error:
XMLHttpRequest cannot load https://fbob.herokuapp.com/osmose_config.zip. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fin-casey.github.io' is therefore not allowed access.

**Comment by jhpoelen** [comment]
added ```Access-Control-Allow-Origin``` to response header:

```
HTTP/1.1 200 OK
< Server: Cowboy
< Connection: keep-alive
< Content-Disposition: attachment; filename=osmose_config.zip
< Access-Control-Allow-Origin: *
```

@FIN-casey please try again

**Comment by jhpoelen** [comment]
Added headers during work session and was able to trigger download for osmose_config.zip . 

```
...
100  1147    0     0  100  1147      0    439  0:00:02  0:00:02 --:--:--   439< HTTP/1.1 200 OK
< Server: Cowboy
< Connection: keep-alive
< Content-Disposition: attachment; filename=osmose_config.zip
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Methods: POST
< Content-Type: application/zip
< Date: Wed, 07 Sep 2016 03:01:59 GMT
< Transfer-Encoding: chunked
< Via: 1.1 vegur
...
```

Suggest to inspect http://stackoverflow.com/a/20830337 to trigger file download for user. 

Please let me know if you have other issues with the configuration api.
