### ISSUE TITLE
API that provides a list of species for a given class

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#59]
List of up to 100 species provided for an order will be ranked by decreasing data richness. 

The species will be extracted from the fishbase api.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @FIN-casey 
Could you please give me an update on this issue?

**Comment by FIN-JBarile** [comment]
@agruss2 Still figuring out how to implement this with @FIN-casey. For now would like to know how to determine data richness. What parameters should we take into consideration, e.g. with Lmax, depth, habitat info? Please advise. Thanks.

**Comment by agruss2** [comment]
@FIN-JBarile @FIN-casey 
First, please note that Jorrit's initial comment should now read: 
"List of up to 100 species provided for a class will be ranked by decreasing data richness.

The species will be extracted from the fishbase api."

**Comment by agruss2** [comment]
@FIN-JBarile @FIN-casey 
Hi think that, to determine data richness, the following could be implemented for every functional group defined by the bridge:
**(1)** The following 18 parameters from FishBase/SeaLifeBase are searched for every species of the functional group considered:
LongevityWild (from the FishBase table “SPECIES”)
K (from the FishBase table “POPGROWTH”)
Loo (from the FishBase table “POPGROWTH”)
to (from the FishBase table “POPGROWTH”)
a (from the FishBase table “POPLW”)
b (from the FishBase table “POPLW”)
Lm (from the FishBase table “MATURITY”)
tm (from the FishBase table “MATURITY”)
RelFecundityMean (from the FishBase table “FECUNDITY”)
SpawningCycles (from the FishBase table “FECUNDITY”)
SexRatiomid (from the FishBase table “SPAWNING”)
PopQB (from the FishBase table “POPQB”)
MaintQB (from the FishBase table “POPQB”)
Mortality (from the FishBase table “POPQB”)
Troph (from the FishBase table “ESTIMATE”)
LengthMin (from the FishBase table “POPLL”)
LengthMax (from the FishBase table “POPLL”)
Eggsdiammod (from the FishBase table “EGGS”)
**(2)** For every species of the functional group considered, presence (1) or absence (0) of each of the above 18 parameters is estimated. 
**(3)** For every species of the functional group considered, data richness is determined as the sum of presence/absence of above 18 parameters. 
For example, if Species X has estimates for all of the above 18 parameters, then data richness of Species X = 18. If Species X has estimates for 16 of the 18 parameters, then data richness of Species X = 16. 

Please let me know if you think this would be a good idea. Many thanks!

**Comment by agruss2** [comment]
@FIN-JBarile @FIN-casey
Hi think that, to determine data richness, the following could be implemented for every functional group defined by the bridge:
(1) The following 18 parameters from FishBase/SeaLifeBase are searched for every species of the functional group considered:
LongevityWild (from the FishBase table “SPECIES”)
K (from the FishBase table “POPGROWTH”)
Loo (from the FishBase table “POPGROWTH”)
to (from the FishBase table “POPGROWTH”)
a (from the FishBase table “POPLW”)
b (from the FishBase table “POPLW”)
Lm (from the FishBase table “MATURITY”)
tm (from the FishBase table “MATURITY”)
RelFecundityMean (from the FishBase table “FECUNDITY”)
SpawningCycles (from the FishBase table “FECUNDITY”)
SexRatiomid (from the FishBase table “SPAWNING”)
PopQB (from the FishBase table “POPQB”)
MaintQB (from the FishBase table “POPQB”)
Mortality (from the FishBase table “POPQB”)
Troph (from the FishBase table “ESTIMATE”)
LengthMin (from the FishBase table “POPLL”)
LengthMax (from the FishBase table “POPLL”)
Eggsdiammod (from the FishBase table “EGGS”)
(2) For every species of the functional group considered, presence (1) or absence (0) of each of the above 18 parameters is estimated.
(3) For every species of the functional group considered, data richness is determined as the sum of presence/absence of above 18 parameters.
For example, if Species X has estimates for all of the above 18 parameters, then data richness of Species X = 18. If Species X has estimates for 16 of the 18 parameters, then data richness of Species X = 16.

Please let me know if you think this would be a good idea. Many thanks!

**Comment by FIN-JBarile** [comment]
@FIN-casey data richness values for each species have been computed using Arnaud's specification above. Please see my e-mail. Thanks.

**Comment by FIN-casey** [comment]
The data richness for fish is now implemented when adding class in functional group. Please send me the nonfish data with data richness when available. THanks

**Comment by FIN-JBarile** [comment]
@FIN-casey Please see my e-mail on where to find the dataset for non-fish with data richness values.

**Comment by FIN-casey** [comment]
Hi THe API is being used by the functionality of adding a class. The species list returned has a maximum of 100 species and sorted by the data richness value. Please verify so we can close the issue.

**Comment by agruss2** [comment]
@FIN-casey @FIN-JBarile @jhpoelen 
I made the same comment in #83 
I think that we should reduce the maximum number of species provided for each class. 100 is too much to my mind; providing so many species for each class to the user will overwhelm them.
What should be the best maximum number of species to provide for each class, according to you? I was thinking that a maximum of 20 species would be reasonable. However, if I missed something and, for any particular reason, you think that the best maximum number of species to provide for each class should be higher, please explain this to me.

**Comment by Dengaloo** [comment]
Yes I agree with Arnaud, less would be good. But which 20?
One question I have in mind is if the species can be presented by maximum length and by habitat? Would that categorizing help in deciding which species might be important in a class?

Sent from my iPad

On May 22, 2017, at 17:20, Arnaud Grüss <notifications@github.com> wrote:

@FIN-casey @FIN-JBarile @jhpoelen
I made the same comment in #83
I think that we should reduce the maximum number of species provided for each class. 100 is too much to my mind; providing so many species for each class to the user will overwhelm them.
What should be the best maximum number of species to provide for each class, according to you? I was thinking that a maximum of 20 species would be reasonable. However, if I missed something and, for any particular reason, you think that the best maximum number of species to provide for each class should be higher, please explain this to me.

**Comment by FIN-JBarile** [comment]
@Dengaloo I think it's the data richness value that determines the species that are included in the list. We followed Arnaud's specifications for data richness [above](https://github.com/jhpoelen/fb-osmose-bridge/issues/59#issuecomment-286300481). @agruss2

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo 
That's correct, Skit. 
I just made another query for the Gulf of Mexico using the UI. 
The list of species provided for each functional group is way too long, and overwhelming. 
Here is what I suggest: we provide a maimum of 20 species **per functional group**. Otherwise, we will get on the user's nerves. 
Could you please implement this @FIN-casey and @FIN-JBarile ? 
Many thanks

**Comment by FIN-casey** [comment]
The species list returned per Class has now a maximum of 20 species.

**Comment by FIN-casey** [comment]
The number of species returned depends on the number of current species of that functional group. The implementation was explained in  [#83](https://github.com/jhpoelen/fb-osmose-bridge/issues/83).

**Comment by agruss2** [comment]
@FIN-casey  The present comment is the same has the last one I posted in #83 
Many thanks for having implemented this, this is very great!
I just ran a test for the Gulf of Mexico to check if a maximum of 20 species per functional group yields satisfying results. 
This test revealed the absence of a key species (Gag (_Mycteroperca microlepis_)) in the table provided in Step 2. 
Therefore, could you please increase the maximum number of species per functional group to 30; and let me know when this is implemented? I will then run a new test to see if the new list of species provided to the user in Step 2 is more satisfying and will keep you posted.

**Comment by FIN-casey** [comment]
@agruss2 The maximum number of species per functional group is now 30. Please verify. Thanks.

**Comment by agruss2** [comment]
@FIN-casey This is perfect, many thanks!
I just ran a test for the Gulf of Mexico to check if a maximum of 30 species per functional group yields satisfying results; and the results are satisfying. In particular, Gag (_Mycteroperca microlepis_) is now included in the table provided in Step 2.
I can therefore close the present issue now.
