### ISSUE TITLE
Add stimulation time step parameters to configuration api 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#62]
make sure that the wizard is able to pass the time step parameters to the configuration api.

**Comment by jhpoelen** [comment]
@agruss2 in the osmose configuration, I see two time related variables:

from osm_all-parameters.csv 
```
simulation.time.ndtPerYear;12
simulation.time.nyear;134
```

Which parameter would you like to be set using the user provided time step parameter? I imagine number of steps a year and number of years of both relevant.

**Comment by agruss2** [comment]
@jhpoelen 
"simulation.time.nyear" sets the number of years of simulation; this is a parameter that the user does not need to provide to the bridge between FishBase/SeaLifeBase and OSMOSE. 
By contrast, the user should indicate the time step of their OSMOSE model to the bridge between FishBase/SeaLifeBase and OSMOSE, i.e.? should indicate the value of the "simulation.time.ndtPerYear" parameter to the bridge between FishBase/SeaLifeBase and OSMOSE. 
simulation.time.ndtPerYear = 12 means that the OSMOSE model has a monthly time step, 
simulation.time.ndtPerYear = 6 means that the OSMOSE model has a two-months time step, 
simulation.time.ndtPerYear = 1 means that the OSMOSE model has an annual time step, etc.

**Comment by jhpoelen** [comment]
@FIN-casey please upgrade the wizard with latest javascript library, so that @agruss2 can test this functionality.

**Comment by FIN-casey** [comment]
I added the time step in the data to be passed on @jhpoelen's API. @agruss2, Please try to enter a value in Step 6.

**Comment by agruss2** [comment]
@FIN-casey @jhpoelen 
I did several tests and it works perfectly !
For instance, if I enter "6" in Step 6, then the parameter "simulation.time.ndtPerYear" is set to 6 in the "osm_all-parameters.csv" file.

**Comment by jhpoelen** [comment]
Glad to hear that the behavior is implemented as desired. Suggest to close this issue.
