### ISSUE TITLE
Simplifying the wizard 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#70]
@FIN-JBarile @FIN-casey 
As discussed through emails, the wizard will be simplified to reduce the burden on the development side, and to faciliate the work of users. 
The main change to be introduced in the wizard is the removal of the option "Let me define functional groups". 
Below, I am going to provide drawings of the successive steps of the new version of the wizard.

**Comment by agruss2** [comment]
Step 1 is unchanged ==> Nothing to do. 

> 
![step 1](https://cloud.githubusercontent.com/assets/16559622/18837496/907472ee-83c9-11e6-91ce-febb3338f5b2.jpg)

**Comment by agruss2** [comment]
What used to be "Step 2" before needs to be removed from the wizard

**Comment by agruss2** [comment]
What used to be "Step 3" after having chosen the option "Define functional groups for me" will be "Step 2". Here is how "Step 3" after having chosen the option "Define functional groups for me"  used to look like:

> 
![step 2](https://cloud.githubusercontent.com/assets/16559622/18837798/be5459a8-83ca-11e6-9a95-fe9ec90b9115.jpg)


Here is what needs to be done now:
(1) The title of this step should now read: "Step 2: Reorganize functional groups" (previously: "Step 3: Reorganize functional groups"); 
(2) Issues #43, #44, #60 and #67, which have been opened for quite some time now, need to be addressed.

**Comment by agruss2** [comment]
What used to be "Step 4" will now be "Step 3". 
Here is how "Step 4" used to look like:

> 
![step 3](https://cloud.githubusercontent.com/assets/16559622/18838041/97c8b3dc-83cb-11e6-9f99-8e7a7f4293e3.jpg)

Here is what needs to be done now:
(1) The title of this step should now read: "Step 3: Order focal functional groups" (previously: "Step 4: Order focal functional groups");
(2) This step needs to be effectively implemented - I am going to create a new issue for this to happen.

**Comment by agruss2** [comment]
What used to be "Step 5" will now be "Step 4".
Here is how "Step 5" used to look like:

> 
![step 4](https://cloud.githubusercontent.com/assets/16559622/18838141/ef553706-83cb-11e6-8e70-70ce1c61bd3c.jpg)

Here is what needs to be done now:
(1) The title of this step should now read: "Step 4: Order background functional groups" (previously: "Step 5: Order background functional groups");
(2) This step needs to be effectively implemented - I am going to create a new issue for this to happen.

**Comment by agruss2** [comment]
What used to be "Step 6" will now be "Step 5".
Here is how "Step 6" used to look like:

> 
![step 5](https://cloud.githubusercontent.com/assets/16559622/18838291/8d385b2e-83cc-11e6-96f1-6920d1506f04.jpg)

Here is what needs to be done now:
(1) Addressing issue #49 .

**Comment by agruss2** [comment]
Here is how the final step should look like:

> 
![final step](https://cloud.githubusercontent.com/assets/16559622/18838326/b0206866-83cc-11e6-970c-aa3a987c5f09.jpg)
==> Nothing to do here.

**Comment by FIN-casey** [comment]
I am done incorporating the changes in UI of the steps
Please check, @agruss2.

**Comment by agruss2** [comment]
@FIN-casey Many thanks, you have done an amazing job. I am going to close the present issue and open new ones.
