### ISSUE TITLE
fishbase table "popqb" not yet populated through fishbase api

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#74]
Table is used in mapping, but does not seem to be populated.

when executing ```curl "https://fishbase.ropensci.org/popqb?SpecCode=120"``` 
the result

```
{"count":0,"returned":0,"data":null,"error":{"message":"no results found"}}
```

is found.

**Comment by agruss2** [comment]
@jhpoelen 
Please asign someone here.

**Comment by jhpoelen** [comment]
Assigning @FIN-JBarile skit because she is the liaison between the ropensci folks and fishbase database dump.

**Comment by jhpoelen** [comment]
Just realized that the error message confused me (also for #77): the table appears to exist, only no data exists for the species requested. Closing issue.
