### ISSUE TITLE
osmose map for "predation.accessibility.stage.threshold.sp" has empty default value

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#75]
@agruss2 Please confirm or update the default value for "predation.accessibility.stage.threshold.sp". The default value is currently an empty string.

**Comment by agruss2** [comment]
See https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv
Thanks.
