### ISSUE TITLE
Add species.lifespan.sp for Seriola dumerili (FishBase ID: 1005) to fishbase

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#78]
In #73, @agruss2 expected 15 for the Amerjack group sp0. Also, you mentioned, none of the three Amberjacks have a reported lifespan in the fishbase table `species` in column `LongevityWild` according to the fishbase api. This is why the configuration api picks the default value from fishbase-mapping.csv and injected the line: `species.lifespan.sp0;0` into osm_params-species.csv . 

@agruss2 please let me know where to find the expected value "15" for the amberjack lifespan.

**Comment by agruss2** [comment]
@jhpoelen 
I found a lifespan of 15 years for amberjacks (more precisely for greater amberjack (Seriola dumerili), which is the reference species of the amberjacks group) in Murie and Parkyn (2008); I am attaching the paper here.

**Comment by jhpoelen** [comment]
If you pack the paper in a zip file, you should be able to upload it.

Since the fishbase api does not yet provide access to the lifespan you found in the Murie and Parkyn (2008) paper (e.g. see https://fishbase.ropensci.org/species?SpecCode=1005), I've assigned this issue to @FIN-JBarile @Dengaloo. I hope that  they can review the paper, add the lifespan to fishbase and propagate the value to be included in the fishbase api.

As far as I can tell the configuration api is working as expected and you'd like to add more data to fishbase. This is why I change to title to Add lifespan ....

**Comment by agruss2** [comment]
@jhpoelen This is excellent; many thanks. Murie and Parkyn (2008) is attached here.
It seems that this project will also help us to identify some information gaps in FishBase/SeaLifeBase, which @Dengaloo and @FIN-JBarile will be able to fill provided that we point them to relevant papers/reports/websites; nice !
[Murie and Parkyn (2008).zip](https://github.com/jhpoelen/fb-osmose-bridge/files/523277/Murie.and.Parkyn.2008.zip)

**Comment by Dengaloo** [comment]
Data being encoded and will be made available in next online update.

**Comment by agruss2** [comment]
I tested the UI today. The desired parameter estimate is now provided by the bridge. Therefore, I am deciding to close the present issue today.
