### ISSUE TITLE
Missing property species.maturity.age.sp0 in osm_params-species.csv

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#79]
@agruss2 noted in #73 that the property species.maturity.age.sp0 was still missing in osm_params-species. 
  
Previously, I changed a test cases to include the property, but omitted to actually include it in the production code. This morning, I regenerated the osmose config with your configuration (wizard prepopulated + switch Red Grouper to background group) and found the following values in the osmose_config.zip:

```csv
species.maturity.age.sp0;4.0
species.maturity.age.sp1;1.0
species.maturity.age.sp2;0.0
```

Please confirm that the property now appears in the generated configuration files.

**Comment by agruss2** [comment]
@jhpoelen I just downloaded a new osmose config zip file and confirm that this change has been implemented; very nice ! Therefore, we can now close the present issue.
