### ISSUE TITLE
unexpected value plankton.size.min.plk0 for Epinephelus morio (FishBase ID: 17)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#81]
In #73, @agruss2 expected ```plankton.size.min.plk0;1``` to appear in the generated configuration file ```osm_param-ltl.csv``` for background group defined by single species Epinephelus morio (FishBase ID: 17). The actual value was 0.0 .

After applied changes described in #80, the actual value of this property is now: ```plankton.size.min.plk0;5.0```. This value is the first non-null value that appears in https://fishbase.ropensci.org/popll?SpecCode=17 .

Please confirm that this is desired, if not, please update your mapping or suggest an alternate mapping implementation.

**Comment by agruss2** [comment]
@jhpoelen The value that was obtained makes sense (as well as the other values in the latest version of the "osm_param-ltl.csv" file obtained from the bridge between FishBase/SeaLifeBase and OSMOSE). Therefore, the present issue can be closed.
