### ISSUE TITLE
Unexpected value plankton.size.max.plk0 for Epinephelus morio (FishBase ID: 17)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#82]
In #73, @agruss2 expected ```plankton.size.max.plk0;125``` to appear in the generated configuration file ```osm_param-ltl.csv``` for background group defined by single species Epinephelus morio (FishBase ID: 17). The actual value was 0.0 .

After applied changes described in #80, the actual value of this property is now: ```plankton.size.max.plk0;90.0```. This value is the first non-null value that appears in https://fishbase.ropensci.org/popll?SpecCode=17 . I was unable to locate the value ```125```  in the column LengthMax for table popll . However, I do see the value appear in the summary http://fishbase.org/summary/17 . This seems to suggest that the mapping specified in ```fishbase-mapping.csv``` might need some attention.

@agruss2 please change the mapping or suggest alternate implementation to map the appropriate values  for plankton.size.max.plk0 .

**Comment by agruss2** [comment]
@jhpoelen The value that was obtained makes sense (as well as the other values in the latest version of the "osm_param-ltl.csv" file obtained from the bridge between FishBase/SeaLifeBase and OSMOSE). Therefore, the present issue can be closed.
