### ISSUE TITLE
UI Step 2 - Issue no. 11 - Information buttons

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#85]
@FIN-casey 
The text associated with a few information buttons needs to be updated, please (see my instructions below).

**Comment by agruss2** [comment]
The text associated with Information button no. 2 should now read:
> To remove a species from a given functional group, deselect it from the column "Species" using the dedicated radio button.

To remove all the species belonging to the same class from a given functional group, deselect the class from the column "Class" using the dedicated radio button; this action will deselect all the species belonging to the class from the column "Species" of the functional group.

**Comment by agruss2** [comment]
The text associated with Information button no. 3 should now read:

**Comment by agruss2** [comment]
The text associated with Information button no. 3 should now read:

**Comment by FIN-casey** [comment]
The changes in the information text are now implemented.

**Comment by agruss2** [comment]
@FIN-casey Many thanks! I can now close the present issue.
