### ISSUE TITLE
Providing egg size estimates to OSMOSE

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#86]
The OSMOSE config file "osm_param-species.csv" provides an estimate of egg size (in cm) for each of the focal functional groups represented in the OSMOSE model. 
Egg size is a parameter that can directly be obtained from FishBase/SeaLifeBase. I noticed that there also is a parameter called eggdiam in the "myersrecruitmentdatabase" FishBase table and I am not sure whether we should use this parameter or the LengthOffspringMin parameter of the "spawning" FishBase table. 
@Dengaloo What do you think?

**Comment by agruss2** [comment]
@Dengaloo I would also like the bridge to provide egg weight estimates to OSMOSE. 
It will be easy to provide estimates of egg weight to OSMOSE from egg size estimates. 
Indeed, if we assume that an egg has a diameter of D cm (and, therefore, a radius r = D/2 cm), then under the assumption that the average density of salt water at the surface is 1.025 kg/l = 1.025 g.cm-3, we get an egg mass of 1.025*4/3.pi.r3 (in g). 
For example, by default, OSMOSE assumes that the size of an egg is 0.1 cm, and, under this assumption, the mass of an egg is 0.00053669 g, considering a sphere with water density. Indeed, if we assume that an egg has a diameter of 0.1 cm (and, therefore, a radius r = 0.05 cm), then under the assumption that the average density of salt water at the surface is 1.025 kg/l = 1.025 g.cm-3, we get an egg mass of 1.025*4/3.pi.r3 = 0.00053669 g.

**Comment by Dengaloo** [comment]
@agruss2 : on eggdiam and LengthOffspringMin, I think eggdiam would more straightforward to use. However, not that the Myers'  database has not been updated since it was absorbed into FishBase. Though, I would think that the data is valid and viable.

**Comment by Dengaloo** [comment]
@agruss2 : on egg weight, that empirical formula could be used if we had the egg diameter, so we can extract that from the Myers'  database. Then if Myers' database does not have a species or a functional group, we might be able to extract that from the EGGS table. In fact, I think we used Myers' database to fill in the egg size field in the EGGS table. So, yes, this is doable.

**Comment by agruss2** [comment]
@Dengaloo It is good to know that we can use eggdiam estimates. 
However, I need to know if we could also use LengthOffspringMin estimates in some case. Indeed, a few OSMOSE models consider focal functional groups that do not lay eggs (e.g., seals). In that case, we would need to look for the LengthOffspringMin parameter in the "spawning" FishBase table, rather than for the eggdiam parameter in the "myersrecruitmentdatabase" FishBase. To do this, some sort of algorithm will need to be implemented in the API.
Please let me know if there would be enough estimates for the LengthOffspringMin parameter in FishBase/SeaLifeBase to derive estimates of "pup size" or "hatchling size" for animals such as seals or sea turtles.

**Comment by agruss2** [comment]
@Dengaloo Regarding my previous comment:
I think that this is not a major issue at all. Actually, only the OSMOSE model of the Strait of Georgia represent seals ...
The thing is that the life cycle and ecology of marine mammals, seabirds and sea turtles is so different from of those of fish that OSMOSE should be substantially recoded to simulate the entire life cycle of marine mammals, seabirds and sea turtles. For this reason, I think that we should emphasize in our project and in the paper that OSMOSE is a modeling platform designed to simulate the entire life cycle of fish and invertebrates currently; and have a bridge between FishBase/SeaLifeBase and OSMOSE that provides estimates for fish and invertebrate functional groups only.

**Comment by agruss2** [comment]
@Dengaloo Looking at your last comment on this issue, I realize that there is an "EGGS" table in FishBase/SeaLifeBase that I am not aware of. Also, I realize that it would make more sense to derive an estimate of egg size for OSMOSE from the "egg size" field of the "EGGS" table.

@Dengaloo and @FIN-JBarile - I am attaching here the version of the "FishBase_DataDictionary" spreadsheet that is currently in our shared Dropbox folder. 
[FishBase_DataDictionary.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/740847/FishBase_DataDictionary.xlsx)
Could you please send me an updated version of the "FishBase_DataDictionary" spreadsheet providing all of the fields of the all the existing tables in FishBase/SeaLifeBase? Many thanks!

**Comment by Dengaloo** [comment]
@agruss2 there are 140 fish and 29 nonfish species with LengthOffspringMin values. So, I suppose that is enough for a model?

OK for taking account only of fish and invertebrates. I am seeing a similar pattern for predator prey relationships, and will take not of this. If we are only considering fishes and invertebrates for one parameter, then we have to do the same thing for the other parameters.

**Comment by FIN-JBarile** [comment]
@agruss2  Here's the updated data dictionary file. Additional sheets refer to EGGS and EGGDEV tables. 
[FishBase_DataDictionary.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/741412/FishBase_DataDictionary.xlsx)

I suggest you identify the tables of interest in FishBase before I generate the corresponding data dictionary. Please know that these are not readily available. May I refer you to the FishBase book online: http://www.fishbase.ca/manual/english/contents.htm? You will find the different suite of tables starting from Nomenclature down to Other tables.

**Comment by agruss2** [comment]
@Dengaloo Yes, I agree. We should focus our efforts on fish and invertebrates from now on, since OSMOSE models usually care only about these marine organisms.

**Comment by agruss2** [comment]
@FIN-JBarile Thanks a lot for the new Data Dictionary that will be very useful! Thanks also for the link to the to the FishBase book. OK, from now on, I will identify the tables of interest in FishBase before coming back to you for you to update the Data Dictionary.

**Comment by agruss2** [comment]
@Dengaloo I am looking at the EGGS table right now, and there is no "egg size" field in this table. For the bridge, should we use the "Eggdiammod" parameter from the EGGS table to derive estimates of egg size and egg diameter for OSMOSE? Or should use another parameter from the EGGS table to do that?

**Comment by Dengaloo** [comment]
@agruss2 : it is the eggdiammod field that measures egg size, we should use that.

**Comment by agruss2** [comment]
@Dengaloo Perfect, thanks ! I just updated the "fishbase-mapping.csv" file. 
I think that we can close the present issue now. Do you agree?

**Comment by agruss2** [comment]
I am closing this issue today.

**Comment by jhpoelen** [comment]
@agruss2 I am assuming that the calculation in https://github.com/jhpoelen/fb-osmose-bridge/issues/86#issuecomment-275958079 accidentally omitted a factor "4" and should read:

```
egg density * egg volume 
~ salt water density * sphere with egg radius
~ salt water density * (4/3) * pi * r^3 
```

**Comment by agruss2** [comment]
@jhpoelen That's correct; thanks!
