### ISSUE TITLE
Providing "Mdiverse" estimates to OSMOSE ? 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#87]
@Dengaloo In the OSMOSE config file entitled "osm_param-natural-mortality.csv", a parameter called "mortality.natural.rate.sp*" is defined for each focal functional group. 
This parameter is the "Mdiverse" parameter in OSMOSE, which is the natural mortality rate of a functional group due to causes not explicitly represented in OSMOSE, such as predation by organisms not explicitly considered in OSMOSE (e.g., marine mammals, seabirds), harmful algal blooms, diseases, senescence, etc. 
I noticed that, in FishBase's "POPQB" table, there is a parameter called "Mortality", which is defined in FishBase's Data Dictionary as the "mortality of juveniles and adults (/y) used for simulating age-structured population."
My question is: Is the "Mortality" parameter from the "POPQB" table accounting only for natural mortality? If so, then I think that it could make sense to extract the "Mortality" parameter from the "POPQB" table to provide an estimate of "Mdiverse"  to OSMOSE. 
What do you think? If you think that this is a relevant idea, then I will update the "fishbase-mapping.csv" file, so that Jorrit can update the API accordingly.

**Comment by Dengaloo** [comment]
@agruss2 : yes the mortality in the POPQB table accounts for natural mortality and does not include fishing mortality.

**Comment by agruss2** [comment]
@Dengaloo Sounds excellent. Can I close the present issue, then?

**Comment by Dengaloo** [comment]
yes ok @agruss2
