### ISSUE TITLE
Regarding the distribution maps provided to OSMOSE

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#88]
@jhpoelen This is a small issue. I have two comments on the issue of distribution maps for OSMOSE:
(1) Among the different inputs that are generated for OSMOSE, there is a "maps" folder containing distribution maps. Currently, the bridge generates inputs for three focal functional groups: "Amberjacks", "KingMackerel", and "SmallPelagics". 
--> The name of the input files in the "maps" folder should be "Amberjacks_1.csv", "KingMackerel_1.csv" and "SmallPelagics_1.csv", instead of "Amberjacks0.csv", "KingMackerel1.csv" and "SmallPelagics2.csv". 
(2) Then, in the "osm_param-movement.csv" config file, the "movement.map*.file" parameters should be set to "maps/Amberjacks_1csv", "maps/KingMackerel_1.csv" and "maps/SmallPelagics_1.csv" instead of "maps/Amberjacks0.csv", "maps/KingMackerel1.csv" and "maps/SmallPelagics2.csv".

**Comment by agruss2** [comment]
@jhpoelen I just made a test and the small issue mentioned here has not been resolved. Could you please ensure that the following is implemented:
(1) The name of the input files in the "maps" folder should be "pelagicmd_1.csv", "pelagiclg_1.csv", "demersalsm_1.csv", etc., instead of "pelagicmd_0.csv", "pelagiclg_1.csv", "demersalsm_2.csv", etc., 
(2) Then, in the "osm_param-movement.csv" config file, the "movement.map*.file" parameters should be set to "maps/pelagicmd_1.csv", "maps/pelagiclg_1.csv", "maps/demersalsm_1.csv", etc., instead of "maps/pelagicmd_0.csv", "maps/pelagiclg_1.csv", "maps/demersalsm_2.csv", etc.,

**Comment by jhpoelen** [comment]
@agruss2  Suggested changes have been applied, please verify.

**Comment by agruss2** [comment]
@jhpoelen The present issue has not been fixed. 
The suffix of all files should be "_1.csv", i.e., "pelagicmd_1.csv", "pelagiclg_1.csv", "demersalsm_1.csv", etc.,

**Comment by jhpoelen** [comment]
@agruss2 thanks for being patient. I misread your proposal for map filenames.

**Comment by jhpoelen** [comment]
Please verify that the proposal has been implemented.

**Comment by agruss2** [comment]
@jhpoelen Perfect, the issue has been fully resolved. I can close it now.
