### ISSUE TITLE
Changes needed in the "osm_param-species.csv" config file 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#92]
@jhpoelen Could you please remove the "species.length2weight.fl.sp*" keys (and corresponding values) from the "osm_param-species.csv" config file?

**Comment by jhpoelen** [comment]
Parameters was removed as requested. Please verify.

**Comment by agruss2** [comment]
The present issue has been resolved; therefore, I am closing it today.
