### ISSUE TITLE
Populate the "osm_param-natural-mortality.csv" config file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#94]
@jhpoelen Please make sure that the API now provides estimates in the "osm_param-natural-mortality.csv" config file for the mortality.natural.rate.sp* parameters.

**Comment by jhpoelen** [comment]
As far as I can tell this parameter is being populated when available. Please verify.

For Gulf of Mexico default values:

```
mortality.natural.rate.sp0;1.0900000333786
mortality.natural.rate.sp1;0.699999988079071
mortality.natural.rate.sp2;0.2
mortality.natural.rate.sp3;0.2
mortality.natural.rate.sp4;0.2
mortality.natural.rate.sp5;1.52999997138977
mortality.natural.rate.sp6;0.2
mortality.natural.rate.sp7;0.2
mortality.natural.rate.sp8;0.2
mortality.natural.rate.sp9;0.2
mortality.natural.rate.sp10;0.2
mortality.natural.rate.sp11;0.2
mortality.natural.rate.sp12;0.2
mortality.natural.rate.sp13;0.75
mortality.natural.rate.sp14;0.2
mortality.natural.rate.sp15;0.409999996423721
mortality.natural.rate.sp16;0.25
mortality.natural.rate.sp17;0.2
mortality.natural.rate.sp18;0.2
mortality.natural.rate.sp19;0.2
mortality.natural.rate.sp20;0.2
mortality.natural.rate.sp21;0.2
```

**Comment by agruss2** [comment]
@jhpoelen It does not surprize me that this parameter is often set to its default value (i.e., 0.2 year-1). Natural mortality estimates are not available for many species in FishBase/SeaLifeBase. 
Therefore, I am considering that the present issue has been resolved and I am closing it today.
