### ISSUE TITLE
Populate the "osm_param-predation.csv" config file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#95]
@jhpoelen Could you please make sure that the API now provides estimates for the following parameters of the "osm_param-predation.csv" config file? 
(1) predation.accessibility.stage.threshold.sp*
(2) predation.efficiency.critical.sp*
(3) predation.ingestion.rate.max.sp*

**Comment by jhpoelen** [comment]
re: (1) and (2) - new features need to be implemented to support mappings described in fishbase-mappings.csv. Will get back to this later.

re: (3) In fishbase-mappsings.csv I noticed ```predation.ingestion.rate.max.osmose.sp```. Note that the parameter name is different than mentioned above (i.e. ```predation.ingestion.rate.max.sp```). Assumed typo and corrected the issue.

**Comment by jhpoelen** [comment]
On second look,  (1) predation.accessibility.stage.threshold.sp* is already present. Leaving only (2) to consider.

**Comment by jhpoelen** [comment]
(2) predation.efficiency.critical.sp is now calculated as described, using mapped parameters ```predation.ingestion.rate.max.sp``` and ```popqb.MaintQB``` (newly introduced in ```fishbase-mapping.csv```.

Please verify.

**Comment by agruss2** [comment]
The present issue has been resolved; many thanks for that! Therefore, I am closing it today.
