### ISSUE TITLE
Populate the "osm_param-species.csv" config file 

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#97]
@jhpoelen Please make sure that the API now provides estimates for the following parameters of the "osm_param-species.csv" config file:
(1) species.egg.size.sp*
(2) species.egg.weight.sp*
(3) species.relativefecundity.sp*
(4) species.sexratio.sp*

**Comment by jhpoelen** [comment]
re: species.egg*: In fishbase-mapping.csv, a non-existent table ```eggs``` is referenced. Could it be that this table has not yet been published through fishbase api ? 

re: relativefecundity - the mapping in fishbase-mapping.csv includes ```fecundity,RelFecundityMean and SpawningCycles,species.relativefecundity.sp```. The term "and" is not yet supported by the configuration api. What do you mean when you say: ```fecundity,RelFecundityMean and SpawningCycles``` ?

re: sexratio - according to a recently generated osmose config.zip, the values are being populated:

e.g. for default Gulf of Mexico

species.sexratio.sp0;52.2
species.sexratio.sp1;75
species.sexratio.sp2;0.5
species.sexratio.sp3;70
species.sexratio.sp4;0.5
species.sexratio.sp5;0.5
species.sexratio.sp6;0.5
species.sexratio.sp7;0.5
species.sexratio.sp8;0.5
species.sexratio.sp9;0.5
species.sexratio.sp10;0.5
species.sexratio.sp11;0.5
species.sexratio.sp12;50
species.sexratio.sp13;52.3
species.sexratio.sp14;0.5
species.sexratio.sp15;50
species.sexratio.sp16;50
species.sexratio.sp17;0.5
species.sexratio.sp18;52
species.sexratio.sp19;0.5
species.sexratio.sp20;0.5
species.sexratio.sp21;50

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo Please address the following comment from Jorrit: "re: species.egg*: In fishbase-mapping.csv, a non-existent table eggs is referenced. Could it be that this table has not yet been published through fishbase api ?"
Moreover, please have a look at the estimates of female:male sex ratios copied/pasted by Jorrit above. Those seem to be extremely high to me. But, perhaps, they make sense based on the ecology of the functional groups/species under consideration. Please analyze this issue and let @jhpoelen and me know. Based on your thoughts, I may decide to set the female:male sex ratio of all focal functional groups to the default value of 0.5. Thanks a lot!

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo Please address the following comment from Jorrit: "re: species.egg*: In fishbase-mapping.csv, a non-existent table eggs is referenced. Could it be that this table has not yet been published through fishbase api ?"
Moreover, please have a look at the estimates of female:male sex ratios copied/pasted by Jorrit above. Those seem to be extremely high to me. But, perhaps, they make sense based on the ecology of the functional groups/species under consideration. Please analyze this issue and let @jhpoelen and me know. Based on your thoughts, I may decide to set the female:male sex ratio of all focal functional groups to the default value of 0.5. Thanks a lot!

**Comment by jhpoelen** [comment]
also see #108 .

**Comment by jhpoelen** [comment]
@agruss2 species.relativefecundity.sp should now be calculated. Please verify.

**Comment by agruss2** [comment]
@jhpoelen Indeed, species.relativefecundity.sp is now being calculated; many thanks!
However, I will soon alter the default value of this parameter in the "fishbase-mapping.csv" file, because it cannot be 0.0. 
More generally, I will rework the "fishbase-mapping.csv" file this weekend to make sure that all the default values provided there are coherent.

**Comment by jhpoelen** [comment]
Glad to hear that the relativefecundity is now calculated. I've opened a separate issue #109 to document the single remaining issue: the missing ```eggs``` fishbase table and am closing this issue.
