### ISSUE TITLE
Add the README file to the "osmose_config.zip" file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#99]
@jhpoelen Today, I started working on the README file, which is attached here. 
[README.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/753468/README.xlsx)
Could you please make sure that the README file is included in the "osmose_config.zip" file that the bridge provides to the user?

**Comment by agruss2** [comment]
@jhpoelen Please note that I am done working with the README file, which is attached here 
[README.xlsx](https://github.com/jhpoelen/fb-osmose-bridge/files/769746/README.xlsx)
Please make sure that this file is included in the "osmose_config.zip" file that the bridge provides to the user. 
Many thanks!

**Comment by jhpoelen** [comment]
Blocked on #100 .

**Comment by jhpoelen** [comment]
added README.xlsx as discussed in #100 . 

Please verify.

**Comment by agruss2** [comment]
@jhpoelen Perfect, thanks a lot! I can close the present issue, then.
